-- Migration 092: Building Catalog and 24-Resource Vectors
CREATE TABLE IF NOT EXISTS building_catalog (
  id TEXT PRIMARY KEY,
  building_type TEXT NOT NULL,
  name TEXT NOT NULL,
  tier INTEGER NOT NULL DEFAULT 1,
  prev_catalog_id TEXT,
  next_catalog_id TEXT,
  category TEXT NOT NULL,
  ownership_class TEXT NOT NULL,
  slot_footprint INTEGER NOT NULL DEFAULT 1,
  cost_credits NUMERIC(18, 6) DEFAULT 0,
  cost_energy NUMERIC(18, 6) DEFAULT 0,
  cost_food NUMERIC(18, 6) DEFAULT 0,
  cost_materials NUMERIC(18, 6) DEFAULT 0,
  cost_components NUMERIC(18, 6) DEFAULT 0,
  cost_compute NUMERIC(18, 6) DEFAULT 0,
  output_credits NUMERIC(18, 6) DEFAULT 0,
  output_energy NUMERIC(18, 6) DEFAULT 0,
  output_food NUMERIC(18, 6) DEFAULT 0,
  output_materials NUMERIC(18, 6) DEFAULT 0,
  output_components NUMERIC(18, 6) DEFAULT 0,
  output_compute NUMERIC(18, 6) DEFAULT 0,
  upkeep_credits NUMERIC(18, 6) DEFAULT 0,
  upkeep_energy NUMERIC(18, 6) DEFAULT 0,
  upkeep_food NUMERIC(18, 6) DEFAULT 0,
  upkeep_materials NUMERIC(18, 6) DEFAULT 0,
  upkeep_components NUMERIC(18, 6) DEFAULT 0,
  upkeep_compute NUMERIC(18, 6) DEFAULT 0,
  operating_credits NUMERIC(18, 6) DEFAULT 0,
  operating_energy NUMERIC(18, 6) DEFAULT 0,
  operating_food NUMERIC(18, 6) DEFAULT 0,
  operating_materials NUMERIC(18, 6) DEFAULT 0,
  operating_components NUMERIC(18, 6) DEFAULT 0,
  operating_compute NUMERIC(18, 6) DEFAULT 0,
  unlocked_perks TEXT[] DEFAULT '{}',
  description TEXT,
  construction_days INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE building_catalog ADD COLUMN IF NOT EXISTS construction_days INTEGER NOT NULL DEFAULT 1;
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS catalog_id TEXT;

INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'restaurant-t1', 'restaurant', 'Bistro & Molecular Diner', 1, NULL, 'restaurant-t2', 'commercial', 'private', 1,
  8500, 120, 0, 0,
  620, 0, 0, 0, 0, 0,
  0.5, 0.3, 0.05, 0.05, 0,
  120, ARRAY['Basic Molecular Dining','Resident Table Turnover']::TEXT[], 'Base foundational dining eatery (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'restaurant-t2', 'restaurant', 'Gourmet Gastronomy Lounge', 2, 'restaurant-t1', 'restaurant-t3', 'commercial', 'private', 1,
  7500, 90, 10, 0,
  620, 0, 0, 0, 0, 0,
  0.9, 0.55, 0.05, 0.05, 0,
  220, ARRAY['Premium Tasting Menu','Corporate Catering Contract']::TEXT[], 'Upscale gastronomy lounge attracting executive patronage.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'restaurant-t3', 'restaurant', 'Planetary Grand Bistro', 3, 'restaurant-t2', NULL, 'commercial', 'private', 1,
  18000, 210, 35, 25,
  620, 0, 0, 0, 0, 0,
  1.6, 1.1, 0.05, 0.05, 0,
  480, ARRAY['District Franchise Rights','Tourism Influx Multiplier (+15%)']::TEXT[], 'Iconic planetary dining destination driving urban tourism.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'retail-store-t1', 'retail-store', 'Retail Hardware Outlet', 1, NULL, 'retail-store-t2', 'commercial', 'private', 1,
  9200, 140, 0, 0,
  710, 0, 0, 0, 0, 0,
  0.4, 0, 0.1, 0.15, 0.05,
  140, ARRAY['Standard Consumer Hardware','Self-Checkout Automated Kiosks']::TEXT[], 'Standard consumer outlet (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'retail-store-t2', 'retail-store', 'Omni-Channel Department Store', 2, 'retail-store-t1', 'retail-store-t3', 'commercial', 'private', 1,
  8200, 110, 15, 0,
  710, 0, 0, 0, 0, 0,
  0.8, 0, 0.1, 0.3, 0.05,
  280, ARRAY['Bulk Wholesale Discounting','Same-Day Drone Delivery Hub']::TEXT[], 'Expanded department store serving multiple municipal sectors.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'retail-store-t3', 'retail-store', 'Cyber-Emporium Flagship', 3, 'retail-store-t2', NULL, 'commercial', 'private', 1,
  21000, 250, 40, 30,
  710, 0, 0, 0, 0, 0,
  1.5, 0, 0.1, 0.6, 0.05,
  580, ARRAY['Augmented Reality Mall Integration','Cross-District Logistics Streamlining']::TEXT[], 'Flagship retail emporium generating massive merchant volume.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'commercial-mall-t1', 'commercial-mall', 'District Galleria Center', 1, NULL, 'commercial-mall-t2', 'commercial', 'public_investment', 4,
  42000, 580, 0, 0,
  4200, 0, 0, 0, 0, 0,
  3.5, 0.8, 0.3, 0.5, 0.6,
  600, ARRAY['Multi-Tenant Merchant Leases','Public Crowdfunding Dividends']::TEXT[], 'Civic commercial mall center.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'commercial-mall-t2', 'commercial-mall', 'Megacity Galleria Complex', 2, 'commercial-mall-t1', NULL, 'commercial', 'public_investment', 4,
  35000, 450, 60, 40,
  4200, 0, 0, 0, 0, 0,
  5.8, 0.8, 0.3, 0.5, 0.6,
  1100, ARRAY['Luxury Brand Concessions','City Sales Tax Rebate (+10% Yield)']::TEXT[], 'Planetary shopping landmark with high shareholder dividends.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'fabrication-plant-t1', 'fabrication-plant', 'CNC Milling Workshop', 1, NULL, 'fabrication-plant-t2', 'manufacturing', 'private', 2,
  13500, 240, 0, 0,
  0, 0, 0, 0, 2.2, 0,
  2, 0, 1.5, 0.1, 0.2,
  150, ARRAY['Automated 5-Axis Milling','Machine Component Stamping']::TEXT[], 'Standard automated component manufacturing (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'fabrication-plant-t2', 'fabrication-plant', 'Advanced Robotic Fab Line', 2, 'fabrication-plant-t1', 'fabrication-plant-t3', 'manufacturing', 'private', 2,
  12000, 180, 25, 0,
  0, 0, 0, 0, 5.2, 0,
  3.4, 0, 2.6, 0.1, 0.2,
  260, ARRAY['Laser Sintering Micro-Assembly','Zero-Defect Quality Control (+20% Yield)']::TEXT[], 'High-throughput robotic line with precision component output.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'fabrication-plant-t3', 'fabrication-plant', 'Quantum Nano-Fabrication Complex', 3, 'fabrication-plant-t2', NULL, 'manufacturing', 'private', 2,
  28000, 380, 60, 50,
  0, 0, 0, 0, 11.5, 0,
  5.5, 0, 4.2, 0.1, 0.2,
  520, ARRAY['Molecular Reconfigurable Fabs','Corporate Machine Blueprint Integration']::TEXT[], 'State-of-the-art quantum nano-foundry.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'chemical-foundry-t1', 'chemical-foundry', 'Catalytic Refining Cell', 1, NULL, 'chemical-foundry-t2', 'manufacturing', 'private', 2,
  14000, 220, 0, 0,
  0, 0, 0, 4.8, 0, 0,
  2.2, 0, 0.8, 0.15, 0.1,
  160, ARRAY['Thermal Hydrocarbon Cracking','Structural Carbon Fiber Weaving']::TEXT[], 'Standard material synthesis plant (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'chemical-foundry-t2', 'chemical-foundry', 'Graphene Alloy Synthesis Plant', 2, 'chemical-foundry-t1', NULL, 'manufacturing', 'private', 2,
  13500, 200, 20, 0,
  0, 0, 0, 10.5, 0, 0,
  3.8, 0, 0.8, 0.15, 0.1,
  290, ARRAY['Graphene Sheet Deposition','Continuous Smelting Loop']::TEXT[], 'High-volume graphene and composite material refinery.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'solar-array-complex-t1', 'solar-array-complex', 'Photovoltaic Collector Field', 1, NULL, 'solar-array-complex-t2', 'energy', 'private', 2,
  10500, 190, 0, 0,
  0, 4.5, 0, 0, 0, 0,
  0, 0, 0.05, 0.1, 0,
  80, ARRAY['Multi-Junction Solar Cells','Automated Heliostat Tracking']::TEXT[], 'Standard solar generation field (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'solar-array-complex-t2', 'solar-array-complex', 'Molten Salt Solar Tower', 2, 'solar-array-complex-t1', 'solar-array-complex-t3', 'energy', 'private', 2,
  9500, 150, 15, 0,
  0, 10.2, 0, 0, 0, 0,
  0, 0, 0.05, 0.1, 0,
  140, ARRAY['24-Hour Thermal Salt Storage','Nighttime Dispatch Balancing']::TEXT[], 'Thermal salt storage array enabling 24-hour round-the-clock generation.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'solar-array-complex-t3', 'solar-array-complex', 'Orbital Reflection Matrix Node', 3, 'solar-array-complex-t2', NULL, 'energy', 'private', 2,
  24000, 320, 45, 20,
  0, 22, 0, 0, 0, 0,
  0, 0, 0.05, 0.1, 0,
  280, ARRAY['Orbital Mirror Microwave Downlink','Zero Transmission Loss Grid Linking']::TEXT[], 'High-density orbital beam collector generating massive power surpluses.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'geothermal-grid-t1', 'geothermal-grid', 'Deep Magmatic Well Tap', 1, NULL, 'geothermal-grid-t2', 'energy', 'civic', 3,
  32000, 480, 0, 0,
  0, 14, 0, 0, 0, 0,
  0, 0, 0.2, 0.4, 0.2,
  300, ARRAY['Supercritical Steam Turbines','District Thermal Heating Grid']::TEXT[], 'Standard municipal geothermal facility (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'geothermal-grid-t2', 'geothermal-grid', 'Supercritical Mantle Generator', 2, 'geothermal-grid-t1', NULL, 'energy', 'civic', 3,
  28000, 380, 50, 0,
  0, 32, 0, 0, 0, 0,
  0, 0, 0.2, 0.4, 0.2,
  520, ARRAY['Mantle Convection Siphoning','City Energy Cost Halved (-50%)']::TEXT[], 'Mantle generator fueling rapid regional industrial growth.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'vertical-farm-t1', 'vertical-farm', 'Aeroponic Tower Array', 1, NULL, 'vertical-farm-t2', 'food', 'private', 2,
  11200, 180, 0, 0,
  0, 0, 3.8, 0, 0, 0,
  1.2, 0, 0.1, 0.1, 0.1,
  110, ARRAY['Optimized LED Wavelength Spectral Tuning','Closed-Loop Nutrient Mist Recycling']::TEXT[], 'Standard urban vertical farm (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'vertical-farm-t2', 'vertical-farm', 'Automated Agro-Bioreactor Hub', 2, 'vertical-farm-t1', NULL, 'food', 'private', 2,
  9800, 140, 18, 0,
  0, 0, 8.5, 0, 0, 0,
  2.1, 0, 0.1, 0.1, 0.1,
  190, ARRAY['Cellular Meat Synthesis Vats','High-Density Protein Blocks']::TEXT[], 'High-volume bioreactor synthesizing cellular agriculture.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'server-farm-t1', 'server-farm', 'Submerged Server Cluster', 1, NULL, 'server-farm-t2', 'compute', 'private', 2,
  14500, 220, 0, 0,
  0, 0, 0, 0, 0, 5,
  3, 0, 0.05, 0.2, 0,
  180, ARRAY['Dielectric Fluid Immersion Cooling','Distributed Vector Crunching']::TEXT[], 'Standard compute cluster (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'server-farm-t2', 'server-farm', 'Quantum Qubit Compute Array', 2, 'server-farm-t1', 'server-farm-t3', 'compute', 'private', 2,
  14000, 210, 35, 30,
  0, 0, 0, 0, 0, 12,
  5.2, 0, 0.05, 0.2, 0,
  340, ARRAY['Cryogenic Superconducting Qubits','Corporate Research Speed Bonus (+25%)']::TEXT[], 'Quantum qubit processor hub accelerating technology R&D.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'server-farm-t3', 'server-farm', 'Photonic Artificial Supercluster', 3, 'server-farm-t2', NULL, 'compute', 'private', 2,
  32000, 420, 75, 80,
  0, 0, 0, 0, 0, 28,
  8.5, 0, 0.05, 0.2, 0,
  680, ARRAY['Optical Photonic Interconnects','Planetary AI Predictive Optimization']::TEXT[], 'Planetary-scale photonic supercluster powering advanced AI automation.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'medical-clinic-t1', 'medical-clinic', 'Community Cyber-Clinic', 1, NULL, 'medical-clinic-t2', 'medical', 'private', 2,
  16000, 240, 0, 0,
  1200, 0, 0, 0, 0, 0,
  1.5, 0.2, 0.1, 0.25, 0.5,
  220, ARRAY['Trauma Stabilization Pods','Automated Cyber-Surgical Arms']::TEXT[], 'Standard bionic medical clinic (EARTH Open Technology).'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'medical-clinic-t2', 'medical-clinic', 'Regenerative Bio-Hospital', 2, 'medical-clinic-t1', NULL, 'medical', 'private', 2,
  15500, 230, 30, 25,
  1200, 0, 0, 0, 0, 0,
  2.8, 0.2, 0.1, 0.25, 0.5,
  420, ARRAY['Organ Cloning Vats','Epidemic Risk Inoculation (-80% Crisis Risk)']::TEXT[], 'Comprehensive bio-hospital securing planetary health scores.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'transit-hyperloop-t1', 'transit-hyperloop', 'District Hyperloop Hub', 1, NULL, 'transit-hyperloop-t2', 'civic', 'public_investment', 3,
  38000, 520, 0, 0,
  3200, 0, 0, 0, 0, 0,
  4, 0, 0.3, 0.5, 0.6,
  500, ARRAY['Supersonic Maglev Transit','Public Crowdfunded Equity Shares']::TEXT[], 'Standard hyperloop terminal.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'transit-hyperloop-t2', 'transit-hyperloop', 'Trans-Continental Express Terminal', 2, 'transit-hyperloop-t1', NULL, 'civic', 'public_investment', 3,
  34000, 450, 65, 45,
  3200, 0, 0, 0, 0, 0,
  6.8, 0, 0.3, 0.5, 0.6,
  950, ARRAY['Heavy Cargo Freight Integration','Trade Tariff Rebate (-25%)']::TEXT[], 'Massive trans-continental hub connecting major metropolitan trade corridors.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'orbital-spaceport-t1', 'orbital-spaceport', 'Sub-Orbital Launch Complex', 1, NULL, 'orbital-spaceport-t2', 'orbital', 'public_investment', 6,
  95000, 1200, 0, 0,
  10500, 0, 0, 0, 0, 0,
  10, 1, 1.2, 1.5, 2.5,
  1500, ARRAY['SSTO Cargo Shuttles','Orbital Satellite Deployment Contracts']::TEXT[], 'First-stage heavy launch platform.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'orbital-spaceport-t2', 'orbital-spaceport', 'Planetary Space Elevator Anchor', 2, 'orbital-spaceport-t1', NULL, 'orbital', 'public_investment', 6,
  85000, 980, 140, 120,
  10500, 0, 0, 0, 0, 0,
  16, 1, 1.2, 1.5, 2.5,
  2800, ARRAY['Carbon Nanotube Tether Car','Zero-G Orbital Manufacturing Bonus (+40%)']::TEXT[], 'Planetary space elevator anchor siphoning orbital commodities directly to earth surface.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'transit-terminus-t1', 'transit-terminus', 'Local Transit Interchange', 1, NULL, NULL, 'civic', 'civic', 4,
  28000, 360, 0, 0,
  0, 0, 0, 0, 0, 0,
  2, 0, 0.2, 0.2, 0,
  260, ARRAY['District Transit Links']::TEXT[], 'Standard municipal transit hub.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'urban-district-module-t1', 'urban-district-module', 'Standard Urban District Module', 1, NULL, NULL, 'civic', 'civic', 0,
  50000, 1000, 0, 0,
  0, 0, 0, 0, 0, 0,
  10, 0, 0.5, 0.5, 0,
  100, ARRAY['+10 Citizen Capacity','+120 Total Slots']::TEXT[], 'Standard horizontal sector expansion module.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'private-estate-plot-t1', 'private-estate-plot', 'Private Estate Plot', 1, NULL, 'private-estate-plot-t2', 'commercial', 'private', 0,
  0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  1, 1, 0, 0, 0.25,
  10, ARRAY['10 Private Building Slots','Basic Life & Domicile Support']::TEXT[], 'Standard residential ground plot and shelter granted to every citizen.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'private-estate-plot-t2', 'private-estate-plot', 'Mezzanine Estate Deck', 2, 'private-estate-plot-t1', 'private-estate-plot-t3', 'commercial', 'private', 0,
  25000, 500, 0, 0,
  0, 0, 0, 0, 0, 0,
  1.5, 1.2, 0, 0, 0.5,
  50, ARRAY['20 Private Building Slots','Enhanced Urban Living']::TEXT[], 'First vertical tier expansion supporting larger enterprise footprints and upgraded residence.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'private-estate-plot-t3', 'private-estate-plot', 'High-Rise Arcology Strata', 3, 'private-estate-plot-t2', 'private-estate-plot-t4', 'commercial', 'private', 0,
  100000, 1500, 2500, 0,
  0, 0, 0, 0, 0, 0,
  4, 1.5, 0, 0, 1,
  200, ARRAY['30 Private Building Slots','High-Rise Luxury Quarters']::TEXT[], 'Advanced vertical spire framework for industrial conglomerates and luxury domicile.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;
INSERT INTO building_catalog (
  id, building_type, name, tier, prev_catalog_id, next_catalog_id, category, ownership_class, slot_footprint,
  cost_credits, cost_materials, cost_components, cost_compute,
  output_credits, output_energy, output_food, output_materials, output_components, output_compute,
  upkeep_energy, upkeep_food, upkeep_materials, upkeep_components, upkeep_compute,
  operating_credits, unlocked_perks, description
) VALUES (
  'private-estate-plot-t4', 'private-estate-plot', 'Orbital Spire Apex', 4, 'private-estate-plot-t3', NULL, 'commercial', 'private', 0,
  500000, 5000, 10000, 500,
  0, 0, 0, 0, 0, 0,
  10, 2, 0, 0, 2.5,
  800, ARRAY['40 Private Building Slots','Planetary Spire Penthouse']::TEXT[], 'Atmospheric apex deck supporting planetary-scale operations and elite domicile.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cost_credits = EXCLUDED.cost_credits,
  cost_materials = EXCLUDED.cost_materials,
  cost_components = EXCLUDED.cost_components,
  cost_compute = EXCLUDED.cost_compute,
  output_credits = EXCLUDED.output_credits,
  output_energy = EXCLUDED.output_energy,
  output_food = EXCLUDED.output_food,
  output_materials = EXCLUDED.output_materials,
  output_components = EXCLUDED.output_components,
  output_compute = EXCLUDED.output_compute,
  upkeep_energy = EXCLUDED.upkeep_energy,
  upkeep_food = EXCLUDED.upkeep_food,
  upkeep_materials = EXCLUDED.upkeep_materials,
  upkeep_components = EXCLUDED.upkeep_components,
  upkeep_compute = EXCLUDED.upkeep_compute,
  operating_credits = EXCLUDED.operating_credits,
  unlocked_perks = EXCLUDED.unlocked_perks,
  description = EXCLUDED.description;

UPDATE buildings
SET catalog_id = building_type || '-t' || COALESCE(tier, 1)
WHERE catalog_id IS NULL;

-- Ensure construction_days is set accurately on all catalog entries based on footprint and tier
UPDATE building_catalog
SET construction_days = GREATEST(1, slot_footprint * COALESCE(tier, 1))
WHERE construction_days = 1 AND slot_footprint > 1;
