-- EARTH ACTIVE MIGRATION: governance thresholds and timing are constitutional
-- policy values, not application constants.

INSERT INTO constitutional_rule_definitions_v5
  (rule_code, article_code, value_type, authority_model, policy_group, amendment_class, allowed_values)
VALUES
  ('CORPORATION.GOVERNANCE.POLICY_QUORUM_BPS', 'CORPORATION_GOVERNANCE', 'RATE_BPS', 'EARTH_DEFAULT_CORPORATION_OVERRIDE', 'GOVERNANCE_POLICY', 'POLICY', '[]'),
  ('CORPORATION.GOVERNANCE.POLICY_APPROVAL_BPS', 'CORPORATION_GOVERNANCE', 'RATE_BPS', 'EARTH_DEFAULT_CORPORATION_OVERRIDE', 'GOVERNANCE_POLICY', 'POLICY', '[]'),
  ('CORPORATION.GOVERNANCE.VOTING_PERIOD_DAYS', 'CORPORATION_GOVERNANCE', 'GAME_DAYS', 'EARTH_DEFAULT_CORPORATION_OVERRIDE', 'GOVERNANCE_POLICY', 'POLICY', '[]'),
  ('CORPORATION.GOVERNANCE.IMPLEMENTATION_DELAY_DAYS', 'CORPORATION_GOVERNANCE', 'GAME_DAYS', 'EARTH_DEFAULT_CORPORATION_OVERRIDE', 'GOVERNANCE_POLICY', 'POLICY', '[]')
ON CONFLICT (rule_code) DO NOTHING;

INSERT INTO constitutional_rule_versions_v5
  (id, rule_code, authority_type, authority_id, version, value_json,
   effective_from_game_day, status)
VALUES
  ('V5-CONST-EARTH-GOV-QUORUM-V1', 'CORPORATION.GOVERNANCE.POLICY_QUORUM_BPS', 'EARTH', 'EARTH', 1, '{"value":"2500"}', 1, 'ACTIVE'),
  ('V5-CONST-EARTH-GOV-APPROVAL-V1', 'CORPORATION.GOVERNANCE.POLICY_APPROVAL_BPS', 'EARTH', 'EARTH', 1, '{"value":"5000"}', 1, 'ACTIVE'),
  ('V5-CONST-EARTH-GOV-PERIOD-V1', 'CORPORATION.GOVERNANCE.VOTING_PERIOD_DAYS', 'EARTH', 'EARTH', 1, '{"value":"3"}', 1, 'ACTIVE'),
  ('V5-CONST-EARTH-GOV-DELAY-V1', 'CORPORATION.GOVERNANCE.IMPLEMENTATION_DELAY_DAYS', 'EARTH', 'EARTH', 1, '{"value":"0"}', 1, 'ACTIVE')
ON CONFLICT (id) DO NOTHING;
