-- EARTH ACTIVE MIGRATION: align persisted registry groups with the runtime catalog.

UPDATE constitutional_rule_definitions_v5
   SET policy_group = CASE
     WHEN rule_code IN (
       'EARTH.CAPACITY.STANDARD',
       'EARTH.CAPACITY.BASE_RATE',
       'EARTH.CAPACITY.PROGRESSIVE_SCHEDULE',
       'EARTH.CAPACITY.HOUSE_PROGRESSIVE_SCHEDULE'
     ) THEN 'CAPACITY_POLICY'
     WHEN rule_code = 'EARTH.HOUSE_INCOME_TAX' THEN 'EARTH_HOUSE_INCOME_TAX'
     WHEN rule_code = 'CORPORATION.HOUSE_INCOME_TAX' THEN 'CORPORATION_HOUSE_INCOME_TAX'
     ELSE policy_group
   END
 WHERE rule_code IN (
   'EARTH.CAPACITY.STANDARD',
   'EARTH.CAPACITY.BASE_RATE',
   'EARTH.CAPACITY.PROGRESSIVE_SCHEDULE',
   'EARTH.CAPACITY.HOUSE_PROGRESSIVE_SCHEDULE',
   'EARTH.HOUSE_INCOME_TAX',
   'CORPORATION.HOUSE_INCOME_TAX'
 );
