-- Migration 122: Add primary_economic_purpose column to building_catalog table and seed values.

ALTER TABLE building_catalog ADD COLUMN IF NOT EXISTS primary_economic_purpose TEXT;

UPDATE building_catalog SET primary_economic_purpose = CASE
  WHEN building_type = 'restaurant' THEN 'Liquid Credit Profit & Resident Consumption'
  WHEN building_type = 'retail-store' THEN 'Retail Sales & Domestic Equipment Turnover'
  WHEN building_type = 'commercial-mall' THEN 'Multi-Tenant Commercial Hub & Shareholder Dividends'
  WHEN building_type = 'residential-habitation-block' THEN 'High-Density Resident Habitation & Citizen Domicile'
  WHEN building_type = 'private-estate-plot' THEN 'Residential Domicile, Life Sustenance & 3D Vertical Estate Capacity'
  WHEN building_type = 'logistics-warehouse' THEN 'Supply Chain Routing & Distribution Cost Reduction'
  WHEN building_type = 'fabrication-plant' THEN 'Precision Component Fabrication & Machine Spare Parts'
  WHEN building_type = 'fabrication-laboratory' THEN 'Advanced Machine Component & High-Tech Assembly'
  WHEN building_type = 'chemical-foundry' THEN 'Structural Material Synthesis & Construction Feedstock'
  WHEN building_type = 'recycling-cooperative' THEN 'Material Reclamation & Component Recovery from Waste'
  WHEN building_type = 'solar-array-complex' THEN 'Clean Photovoltaic Energy & Grid Baseline'
  WHEN building_type = 'battery-storage-array' THEN 'Surplus Energy Reserve & Grid Stability Buffer'
  WHEN building_type = 'geothermal-grid' THEN 'Municipal Baseload Energy & Citizen UBI Funding'
  WHEN building_type = 'urban-climate-grid' THEN 'District Thermal Regulation & Climate Mitigation'
  WHEN building_type = 'municipal-power-exchange' THEN 'Regional Power Distribution & Public Grid Revenue'
  WHEN building_type = 'vertical-farm' THEN 'Fresh Protein, Organic Nutrition & Urban Food Reserves'
  WHEN building_type = 'biotech-greenhouse' THEN 'High-Yield Organic Biomass & Pharmaceutical Feedstock'
  WHEN building_type = 'public-food-reserve' THEN 'Strategic Municipal Food Security & Emergency Nutrition'
  WHEN building_type = 'server-farm' THEN 'High-Throughput Quantum & Neural Compute Generation'
  WHEN building_type = 'data-services-studio' THEN 'Commercial Data Telemetry & Analytics Compute Services'
  WHEN building_type = 'civic-data-network' THEN 'Municipal High-Speed Data & Administration Efficiency'
  WHEN building_type = 'medical-clinic' THEN 'Urban Healthcare, Longevity & Disease Protection'
  WHEN building_type = 'municipal-medical-center' THEN 'Comprehensive Regional Healthcare & Health Resilience'
  WHEN building_type = 'medical-research-campus' THEN 'Planetary Medical Innovation & Vaccine R&D Dividends'
  WHEN building_type = 'water-reclamation-plant' THEN 'Municipal Water Recycling & Resource Loss Mitigation'
  WHEN building_type = 'water-sanitation-authority' THEN 'Municipal Water Purity & Sanitation Infrastructure'
  WHEN building_type = 'regional-waterworks-consortium' THEN 'Large-Scale Water Infrastructure & Utility Dividends'
  WHEN building_type = 'transit-terminus' THEN 'Municipal Transit and District Connectivity'
  WHEN building_type = 'urban-district-module' THEN 'Municipal Land & Citizen Capacity Expansion'
  WHEN building_type = 'transit-hyperloop' THEN 'High-Speed Logistics & Public Passenger Dividends'
  WHEN building_type = 'orbital-spaceport' THEN 'Orbital Shuttles, Off-World Mining Logistics & High Prestige'
  WHEN building_type = 'planetary-freight-terminal' THEN 'Heavy Inter-City Freight Logistics & Commercial Dividends'
  WHEN building_type = 'orbital-communications-array' THEN 'Orbital Satellite Relay & Telecommunication Dividends'
  WHEN building_type = 'advanced-materials-foundry' THEN 'Heavy Structural Alloys & Aerospace Materials Dividends'
  WHEN building_type = 'metropolitan-housing-trust' THEN 'Investor-Funded Affordable Housing & Citizen Influx'
  WHEN building_type = 'agricultural-reserve-network' THEN 'Regional Strategic Food Reserves & Agricultural Dividends'
  WHEN building_type = 'carbon-capture-atmosphere-works' THEN 'Environmental Carbon Removal & Ecological Stability'
  WHEN building_type = 'inter-city-data-exchange' THEN 'Inter-City High-Bandwidth Data & Telemetry Dividends'
  WHEN building_type = 'civic-housing-authority' THEN 'Public Affordable Housing & Citizen Population Influx'
  WHEN building_type = 'public-education-campus' THEN 'Workforce Skill Development & Research Capability'
  WHEN building_type = 'emergency-response-command' THEN 'City Emergency Command & Disaster Resilience'
  WHEN building_type = 'municipal-resource-exchange' THEN 'District Resource Clearing & Commodity Balancing'
  WHEN building_type = 'atmospheric-processing-station' THEN 'Urban Air Purification & Environmental Health'
  ELSE COALESCE(primary_economic_purpose, CASE WHEN ownership_class = 'civic' THEN 'Municipal Infrastructure & Citizen Dividends' ELSE 'Commercial Production & Resident Consumption' END)
END;
