import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

test('database migrations: verify sequential migration files, schema.sql, functions.sql, and schema manifest version', () => {
  const migrationsDir = path.resolve('db/migrations');
  const manifestPath = path.resolve('db/schema-manifest.json');
  const schemaPath = path.resolve('db/schema.sql');
  const functionsPath = path.resolve('db/functions.sql');

  const files = fs.readdirSync(migrationsDir).filter((f) => f.endsWith('.sql')).sort();
  assert.ok(files.length >= 83, `Expected at least 83 migrations, found ${files.length}`);
  assert.equal(files[0], '001_initial.sql');
  assert.equal(files.at(-1), '194_proposal_limits_and_challenges.sql');

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  assert.equal(manifest.migrationVersion, 194, 'Manifest version must match latest migration version (194)');

  const schema = fs.readFileSync(schemaPath, 'utf8');
  assert.match(schema, /reconciled through migration 194/);
  assert.ok(manifest.requiredTables.proposal_challenge_authorities, 'Manifest must contain challenge authorities');
  assert.ok(manifest.requiredIndexes.includes('proposals_active_conflict_idx'), 'Manifest must contain active conflict protection');
  assert.ok(manifest.requiredTables.proposals.includes('decision_status'), 'Proposals must expose decision status');
  assert.ok(manifest.requiredTables.governance_rules.includes('effective_from_game_day'), 'Governance rules must expose effective start day');
  const effectiveRanges = fs.readFileSync(path.resolve('db/migrations/192_governance_rule_effective_ranges.sql'), 'utf8');
  assert.match(effectiveRanges, /effective_to_game_day/);
  assert.ok(manifest.requiredTables.proposal_action_requirements, 'Manifest must contain proposal action requirements');
  const stateMachine = fs.readFileSync(path.resolve('db/migrations/193_proposal_state_machine.sql'), 'utf8');
  assert.match(stateMachine, /decision_status/);
  assert.ok(manifest.requiredTables.proposal_actions, 'Manifest must contain typed proposal actions');
  assert.ok(manifest.requiredTables.proposal_vote_totals, 'Manifest must contain proposal vote totals');
  assert.ok(manifest.requiredIndexes.includes('memberships_city_joined_human_idx'), 'Manifest must contain city electorate index');
  const electorate = fs.readFileSync(path.resolve('db/migrations/189_proposal_electorate_aggregation.sql'), 'utf8');
  assert.match(electorate, /ON CONFLICT \(proposal_id\) DO NOTHING/);
  const proposalContract = fs.readFileSync(path.resolve('db/migrations/188_proposal_contract_snapshots.sql'), 'utf8');
  assert.match(proposalContract, /governance_snapshot JSONB/);
  assert.match(proposalContract, /action_snapshot JSONB/);
  const proposalVoting = fs.readFileSync(path.resolve('db/migrations/187_proposal_voting_correctness.sql'), 'utf8');
  assert.match(proposalVoting, /governance_rules_one_active_category/);
  assert.match(proposalVoting, /ROW_NUMBER\(\)/);
  assert.ok(manifest.requiredTables.scheduler_runs, 'Manifest must contain scheduler run observability');
  const schedulerRuns = fs.readFileSync(path.resolve('db/migrations/186_scheduler_run_observability.sql'), 'utf8');
  assert.match(schedulerRuns, /CREATE TABLE IF NOT EXISTS scheduler_runs/);
  assert.match(schedulerRuns, /settlement_watermark_before/);
  assert.match(schedulerRuns, /outbox_events_delivered/);
  assert.ok(manifest.requiredTables.market_batch_runs, 'Manifest must contain market batch runs');
  const timedBatches = fs.readFileSync(path.resolve('db/migrations/184_scheduled_actions_and_market_batches.sql'), 'utf8');
  assert.match(timedBatches, /CREATE OR REPLACE FUNCTION earth_claim_scheduled_actions/);
  assert.match(timedBatches, /FOR UPDATE SKIP LOCKED/);
  assert.match(timedBatches, /CREATE TABLE IF NOT EXISTS market_batch_runs/);
  assert.match(timedBatches, /CREATE OR REPLACE FUNCTION earth_claim_market_batch/);
  const watermark = fs.readFileSync(path.resolve('db/migrations/183_scheduler_settlement_watermark.sql'), 'utf8');
  assert.match(watermark, /CREATE OR REPLACE FUNCTION earth_settlement_watermark/);
  assert.match(watermark, /MIN\(day\) - 1/);
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS buildings'), 'Canonical schema.sql must define buildings');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS houses'), 'Canonical schema.sql must define houses');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_assets'), 'Canonical schema.sql must define V2 assets');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_accounts'), 'Canonical schema.sql must define V2 accounts');
  assert.ok(!schema.includes('character_lineage'), 'Canonical schema.sql must not include dropped character_lineage');
  assert.ok(!schema.includes('asset_ownership_events'), 'Canonical schema.sql must not include dropped asset_ownership_events');
  assert.ok(manifest.requiredTables.building_settlement_journals, 'Manifest must contain building_settlement_journals');
  assert.ok(manifest.requiredTables.human_technology_subscriptions, 'Manifest must contain human technology subscriptions');
  assert.ok(manifest.requiredTables.owner_registry.includes('economic_id'), 'Owner registry must expose compact economic IDs');
  assert.ok(manifest.requiredUniqueConstraints.some((key) => key.join(':') === 'owner_registry:economic_id'), 'Economic IDs must be unique');
  assert.ok(manifest.requiredTables.economic_assets, 'Manifest must contain the V2 asset catalog');
  assert.ok(manifest.requiredTables.economic_assets.includes('scale'), 'V2 assets must define fixed-point scale');
  assert.ok(manifest.requiredTables.economic_assets.includes('decimals'), 'V2 assets must define display precision');
  assert.ok(manifest.requiredTables.economic_accounts, 'Manifest must contain unified economic accounts');
  assert.ok(manifest.requiredTables.economic_transactions, 'Manifest must contain V2 transactions');
  assert.ok(manifest.requiredTables.economic_entries, 'Manifest must contain V2 entries');
  assert.ok(fs.readFileSync(path.resolve('db/migrations/154_economy_v2_idempotency.sql'), 'utf8').includes('ON CONFLICT (correlation_id) DO NOTHING'), 'V2 idempotency must be database-enforced');
  const posting = fs.readFileSync(path.resolve('db/migrations/155_economy_v2_posting_primitives.sql'), 'utf8');
  assert.match(posting, /CREATE OR REPLACE FUNCTION earth_post_transaction/);
  assert.match(posting, /CREATE OR REPLACE FUNCTION earth_post_settlement_batch/);
  assert.match(posting, /ORDER BY a\.id\s+FOR UPDATE/);
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_transactions'), 'Canonical schema.sql must define V2 transactions');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_entries'), 'Canonical schema.sql must define V2 entries');
  assert.ok(manifest.requiredIndexes.includes('economic_accounts_owner_asset_idx'), 'Manifest must contain the owner/asset account index');
  assert.ok(manifest.requiredTables.daily_settlement_profiles.includes('owner_economic_id'), 'Profiles must use compact economic owners');
  assert.ok(fs.readFileSync(path.resolve('db/migrations/156_economy_v2_bulk_settlement_profiles.sql'), 'utf8').includes('CREATE OR REPLACE FUNCTION earth_rebuild_dirty_profiles'), 'Profiles must have a bulk rebuild primitive');
  assert.ok(manifest.requiredTables.settlement_effects, 'Manifest must contain settlement effects');
  assert.ok(manifest.requiredTables.settlement_effect_nets, 'Manifest must contain phase-scoped effect nets');
  const nets = fs.readFileSync(path.resolve('db/migrations/158_economy_v2_phase_nets.sql'), 'utf8');
  assert.match(nets, /CREATE OR REPLACE FUNCTION earth_net_settlement_effects/);
  assert.match(nets, /WHERE e\.game_day = p_game_day/);
  const bulkPosting = fs.readFileSync(path.resolve('db/migrations/159_economy_v2_bulk_settlement_posting.sql'), 'utf8');
  assert.match(bulkPosting, /CREATE OR REPLACE FUNCTION earth_post_settlement_phase/);
  assert.match(bulkPosting, /SUM\(delta\)::BIGINT AS delta/);
  assert.match(bulkPosting, /UPDATE economic_accounts a/);
  assert.ok(manifest.requiredTables.daily_settlement_phase_runs.includes('lease_owner'), 'Settlement phases must track lease ownership');
  const phases = fs.readFileSync(path.resolve('db/migrations/160_economy_v2_resumable_settlement_phases.sql'), 'utf8');
  assert.match(phases, /CREATE OR REPLACE FUNCTION earth_claim_settlement_phase/);
  assert.match(phases, /CREATE OR REPLACE FUNCTION earth_complete_settlement_phase/);
  const dayCoordination = fs.readFileSync(path.resolve('db/migrations/182_scheduler_day_coordination.sql'), 'utf8');
  for (const functionName of ['earth_claim_settlement_day', 'earth_heartbeat_settlement_day', 'earth_complete_settlement_day', 'earth_fail_settlement_day']) assert.match(dayCoordination, new RegExp(`CREATE OR REPLACE FUNCTION ${functionName}`));
  assert.match(dayCoordination, /status\s*:=\s*'busy'/);
  assert.match(dayCoordination, /lease_heartbeat_at.*> stale_before/);
  assert.ok(manifest.requiredTables.daily_settlement_runs.includes('shard_count'), 'Settlement runs must persist shard configuration');
  const shards = fs.readFileSync(path.resolve('db/migrations/161_economy_v2_shard_configuration.sql'), 'utf8');
  assert.match(shards, /CREATE OR REPLACE FUNCTION earth_settlement_shard/);
  assert.match(shards, /CREATE OR REPLACE FUNCTION earth_reduce_shared_settlement_effects/);
  assert.ok(manifest.requiredTables.economic_owner_totals, 'Manifest must contain cumulative economic totals');
  const totals = fs.readFileSync(path.resolve('db/migrations/162_economy_v2_owner_totals.sql'), 'utf8');
  assert.match(totals, /CREATE TRIGGER economic_entries_owner_totals/);
  assert.ok(manifest.requiredTables.settlement_rate_segments, 'Manifest must contain intraday rate segments');
  assert.ok(manifest.requiredTables.economy_shadow_openings, 'Manifest must contain shadow opening balances');
  assert.ok(manifest.requiredTables.economy_shadow_reconciliations, 'Manifest must contain shadow reconciliation results');
  assert.ok(manifest.requiredTables.economy_shadow_runs, 'Manifest must contain shadow run summaries');
  assert.ok(manifest.requiredTables.economic_entry_partitions, 'Manifest must contain partition provisioning metadata');
  const rates = fs.readFileSync(path.resolve('db/migrations/163_economy_v2_rate_segments.sql'), 'utf8');
  assert.match(rates, /CREATE OR REPLACE FUNCTION earth_calculate_intraday_rate_units/);
  assert.match(rates, /LEAD\(minute\)/);
  const partitioning = fs.readFileSync(path.resolve('db/migrations/164_economy_v2_partition_entries.sql'), 'utf8');
  assert.match(partitioning, /PARTITION BY RANGE \(game_day\)/);
  assert.match(partitioning, /economic_entries_default/);
  assert.doesNotMatch(partitioning, /PARTITION BY RANGE.*economic_transactions/);
  const integrity = fs.readFileSync(path.resolve('db/migrations/165_economy_v2_integrity_checks.sql'), 'utf8');
  assert.match(integrity, /CREATE OR REPLACE FUNCTION earth_integrity_report/);
  assert.match(integrity, /economic_account_owner_missing/);
  assert.match(integrity, /CREATE OR REPLACE FUNCTION earth_validate_settlement_day/);
  const stabilization = fs.readFileSync(path.resolve('db/migrations/166_stabilize_profile_settlement_path.sql'), 'utf8');
  assert.match(stabilization, /Profile acceleration is unsafe/);
  assert.match(stabilization, /public_investment/);
  assert.match(stabilization, /gross_credits_inflow/);
  assert.ok(manifest.requiredTables.economic_account_types, 'Manifest must contain explicit account semantics');
  const semantics = fs.readFileSync(path.resolve('db/migrations/167_economy_v2_account_semantics.sql'), 'utf8');
  assert.match(semantics, /ISSUANCE/);
  assert.match(semantics, /CONSUMPTION_SINK/);
  assert.match(semantics, /allows_negative/);
  assert.ok(manifest.requiredTables.economic_account_migrations, 'Manifest must contain legacy account mappings');
  const mappings = fs.readFileSync(path.resolve('db/migrations/168_economy_v2_legacy_account_mapping.sql'), 'utf8');
  assert.match(mappings, /account-city-operations/);
  assert.match(mappings, /MARKET_CLEARING/);
  assert.match(mappings, /account-market-clearing/);
  assert.match(mappings, /resource:/);
  const shardUnification = fs.readFileSync(path.resolve('db/migrations/169_economy_v2_unify_shards.sql'), 'utf8');
  assert.match(shardUnification, /p_shard_count > 64/);
  assert.match(shardUnification, /earth_settlement_shard\(NEW\.owner_economic_id, 64\)/);
  assert.ok(manifest.requiredTables.economic_accounts.includes('settlement_shard'), 'Accounts must support shard-local clearing');
  const clearing = fs.readFileSync(path.resolve('db/migrations/170_economy_v2_shard_clearing_accounts.sql'), 'utf8');
  assert.match(clearing, /economic_accounts_shard_clearing_uq/);
  assert.match(clearing, /earth_get_shard_clearing_account/);
  const invariants = fs.readFileSync(path.resolve('db/migrations/171_economy_v2_transaction_invariants.sql'), 'utf8');
  assert.match(invariants, /DEFERRABLE INITIALLY DEFERRED/);
  assert.match(invariants, /pg_inherits/);
  assert.match(invariants, /CREATE CONSTRAINT TRIGGER economic_entries_balance_check/);
  assert.match(invariants, /at least two final net entries/);
  const ownerTotals = fs.readFileSync(path.resolve('db/migrations/172_economy_v2_owner_totals_net_projection.sql'), 'utf8');
  assert.match(ownerTotals, /GROUP BY e\.transaction_id, a\.owner_economic_id, a\.asset_id/);
  assert.match(ownerTotals, /SUM\(e\.delta\)::BIGINT AS net_delta/);
  assert.match(ownerTotals, /internal transfer/i);
  const rateSegments = fs.readFileSync(path.resolve('db/migrations/173_economy_v2_rate_segment_baselines.sql'), 'utf8');
  assert.match(rateSegments, /daily_baseline/);
  assert.match(rateSegments, /game_day < p_game_day/);
  assert.match(rateSegments, /earth_record_settlement_rate_segment\(v_owner_economic_id/);
  assert.match(rateSegments, /ROUND\(SUM\(COALESCE\(rate, 0\)/);
  const invalidation = fs.readFileSync(path.resolve('db/migrations/174_economic_state_change_invalidation.sql'), 'utf8');
  assert.match(invalidation, /CREATE OR REPLACE FUNCTION earth_economic_state_changed/);
  assert.match(invalidation, /SET status = 'dirty'/);
  assert.match(invalidation, /earth_record_rate_change/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/real-estate-postgres.ts'), 'utf8'), /earth_economic_state_changed/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/daily-automation.ts'), 'utf8'), /construction_completed/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/daily-automation.ts'), 'utf8'), /technology_upgrade/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/lifecycle-postgres.ts'), 'utf8'), /ownership_transfer_in/);
  const buildingEconomics = fs.readFileSync(path.resolve('db/migrations/175_canonical_building_economics.sql'), 'utf8');
  assert.match(buildingEconomics, /CREATE OR REPLACE FUNCTION earth_calculate_building_economics/);
  assert.match(buildingEconomics, /effective_output_multiplier/);
  assert.match(buildingEconomics, /effective_cost_multiplier/);
  assert.match(buildingEconomics, /building_catalog/);
  assert.match(buildingEconomics, /CROSS JOIN LATERAL earth_calculate_building_economics/);
  assert.match(buildingEconomics, /earth_record_settlement_rate_segment/);
  assert.match(buildingEconomics, /same canonical calculator/);
  assert.match(buildingEconomics, /asset\.scale/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/building-settlement-engine.ts'), 'utf8'), /earth_calculate_building_economics/);
  assert.ok(manifest.requiredTables.economic_policy_rules, 'Manifest must contain canonical policy rules');
  assert.ok(manifest.requiredTables.economic_ownership_classes, 'Manifest must contain canonical ownership classes');
  const policyRules = fs.readFileSync(path.resolve('db/migrations/176_canonical_policy_and_ownership_rules.sql'), 'utf8');
  const policyValues = fs.readFileSync(path.resolve('db/migrations/177_finalize_policy_rules.sql'), 'utf8');
  assert.match(policyRules, /CREATE TABLE IF NOT EXISTS economic_policy_rules/);
  assert.match(policyRules, /CREATE TABLE IF NOT EXISTS economic_ownership_classes/);
  assert.match(policyRules, /JOIN economic_policy_rules policy/);
  assert.match(policyRules, /'halted', 0\.00, 0\.20, 0\.10/);
  assert.match(policyRules, /'overclock', 1\.60, 1\.90, 3\.00/);
  assert.match(policyValues, /'overclock', 1\.60, 1\.90, 3\.00/);
  assert.match(policyValues, /decay_multiplier = 0\.10/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/building-settlement-engine.ts'), 'utf8'), /economic_policy_rules policy/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/real-estate-catalog.ts'), 'utf8'), /'overclock'/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/building-settlement-engine.ts'), 'utf8'), /economic_decay_multiplier/);
  const profileOrchestration = fs.readFileSync(path.resolve('cloudflare/src/daily-settlement-profiles.ts'), 'utf8');
  assert.match(profileOrchestration, /earth_rebuild_dirty_profiles\(\$1::smallint, \$2::bigint\)/);
  assert.doesNotMatch(profileOrchestration, /SELECT owner_id, owner_kind FROM daily_settlement_profiles/);
  const scheduler = fs.readFileSync(path.resolve('cloudflare/src/scheduler-postgres.ts'), 'utf8');
  assert.match(scheduler, /earth_claim_settlement_phase/);
  assert.match(scheduler, /earth_complete_settlement_phase/);
  assert.match(scheduler, /runResumableSettlementDay/);
  assert.match(scheduler, /createDailySettlementPhaseRegistry/);
  assert.match(scheduler, /earth_claim_settlement_day/);
  assert.match(scheduler, /status: 'partial'/);
  assert.match(scheduler, /earth_complete_settlement_day/);
  assert.doesNotMatch(scheduler, /runDailyPhase\(/);
  assert.doesNotMatch(scheduler, /resumableSettlement\s*=/);
  assert.match(scheduler, /captureEconomyShadowOpening/);
  assert.match(scheduler, /reconcileEconomyShadowDay/);
  assert.match(scheduler, /repository\.transaction\(async \(tx\) => \{/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/index.ts'), 'utf8'), /runSchedulerHeartbeat\(repository, _event\.scheduledTime/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/health.ts'), 'utf8'), /earth_settlement_watermark/);
  const resourceLedger = fs.readFileSync(path.resolve('cloudflare/src/resource-ledger-postgres.ts'), 'utf8');
  assert.match(resourceLedger, /postEconomicResourceMutation/);
  assert.match(resourceLedger, /earth_post_transaction/);
  assert.match(resourceLedger, /economic_account_migrations/);
  const bankBridge = fs.readFileSync(path.resolve('db/migrations/178_economy_v2_bank_posting_bridge.sql'), 'utf8');
  assert.match(bankBridge, /earth_post_transaction/);
  assert.match(bankBridge, /earth_transfer_credits/);
  const shadow = fs.readFileSync(path.resolve('db/migrations/179_economy_v2_shadow_reconciliation.sql'), 'utf8');
  assert.match(shadow, /CREATE TABLE IF NOT EXISTS economy_shadow_openings/);
  assert.match(shadow, /CREATE TABLE IF NOT EXISTS economy_shadow_reconciliations/);
  assert.match(shadow, /CREATE TABLE IF NOT EXISTS economy_shadow_runs/);
  assert.match(shadow, /difference_kind/);
  assert.match(shadow, /absolute_difference_units/);
  const partitionProvisioning = fs.readFileSync(path.resolve('db/migrations/180_economy_v2_partition_provisioning.sql'), 'utf8');
  assert.match(partitionProvisioning, /CREATE TABLE IF NOT EXISTS economic_entry_partitions/);
  assert.match(partitionProvisioning, /earth_provision_economic_entry_partitions/);
  assert.match(partitionProvisioning, /DETACH PARTITION economic_entries_default/);
  assert.match(partitionProvisioning, /ATTACH PARTITION economic_entries_default DEFAULT/);
  const integrityReport = fs.readFileSync(path.resolve('db/migrations/181_economy_v2_integrity_report.sql'), 'utf8');
  for (const check of ['missing_default_economic_account', 'multiple_active_default_economic_account', 'account_asset_mismatch', 'wrong_account_shard', 'wrong_profile_shard', 'balance_vs_ledger_mismatch', 'stale_dirty_profile', 'stale_clean_profile', 'incomplete_entry_partition_provisioning', 'completed_day_effects_remaining', 'economic_owner_totals_mismatch', 'source_sink_conservation_failure', 'v2_legacy_reconciliation_difference']) assert.match(integrityReport, new RegExp(check));
  assert.doesNotMatch(integrityReport, /business_owner_missing_registry/);
  assert.match(integrityReport, /v2_legacy_reconciliation_unexplained_run/);
  const performanceBenchmark = fs.readFileSync(path.resolve('scripts/benchmark-economy-v2.mjs'), 'utf8');
  assert.match(performanceBenchmark, /generate_series\(1, \$1::BIGINT\)/);
  assert.match(performanceBenchmark, /lockContentionProbe/);
  assert.match(fs.readFileSync(path.resolve('cloudflare/src/economic-entry-partitions.ts'), 'utf8'), /earth_provision_economic_entry_partitions/);
  assert.match(scheduler, /provisionEconomicEntryPartitions/);
  const economicRoutes = fs.readFileSync(path.resolve('cloudflare/src/economic-routes.ts'), 'utf8');
  assert.match(economicRoutes, /\/api\/economy\/balances/);
  assert.match(economicRoutes, /\/api\/economy\/transactions/);
  assert.match(economicRoutes, /displayUnits/);
  assert.match(economicRoutes, /economic_entries/);
  assert.match(economicRoutes, /asset_scale/);
  assert.match(economicRoutes, /delta_units/);
  const flutterFinanceApi = fs.readFileSync(path.resolve('flutter_client/lib/core/api/earth_api_personal_finance.dart'), 'utf8');
  assert.match(flutterFinanceApi, /\/api\/economy\/balances/);
  assert.match(fs.readFileSync(path.resolve('flutter_client/lib/features/finance/personal_finance_panel.dart'), 'utf8'), /v2Credit/);
  assert.match(fs.readFileSync(path.resolve('scripts/verify-economy-v2-cutover.mjs'), 'utf8'), /legacyMutationCallers/);
  assert.match(fs.readFileSync(path.resolve('package.json'), 'utf8'), /db:verify:economy-cutover/);
  const effects = fs.readFileSync(path.resolve('db/migrations/157_economy_v2_settlement_effects.sql'), 'utf8');
  assert.match(effects, /CREATE UNLOGGED TABLE IF NOT EXISTS settlement_effects/);
  assert.match(effects, /owner_economic_id BIGINT/);
  assert.ok(!manifest.requiredTables.businesses, 'Manifest must not contain the removed Business table');

  const functions = fs.readFileSync(functionsPath, 'utf8');
  assert.ok(functions.includes('CREATE OR REPLACE FUNCTION earth_transfer_credits'), 'functions.sql must contain earth_transfer_credits');

  const economyV2 = fs.readFileSync(path.resolve('db/migrations/150_economy_v2_compact_owner_ids.sql'), 'utf8');
  assert.match(economyV2, /ADD COLUMN IF NOT EXISTS economic_id BIGINT/);
  assert.match(economyV2, /owner_registry_economic_id_seq/);
  assert.match(economyV2, /owner_registry_economic_id_key/);
  assert.doesNotMatch(economyV2, /DROP TABLE/i, 'Plan 1 must not drop domain or legacy accounting tables');
  assert.doesNotMatch(economyV2, /ALTER TABLE (humans|cities|corporations)\s+.*DROP/i, 'Plan 1 must not rewrite domain IDs');
});
