import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

test('database migrations: verify sequential migration files, schema.sql, functions.sql, and schema manifest version', () => {
  const migrationsDir = path.resolve('db/migrations');
  const manifestPath = path.resolve('db/schema-manifest.json');
  const schemaPath = path.resolve('db/schema.sql');
  const functionsPath = path.resolve('db/functions.sql');

  const files = fs.readdirSync(migrationsDir).filter((f) => f.endsWith('.sql')).sort();
  assert.ok(files.length >= 83, `Expected at least 83 migrations, found ${files.length}`);
  assert.equal(files[0], '001_initial.sql');
  assert.equal(files.at(-1), '165_economy_v2_integrity_checks.sql');

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  assert.equal(manifest.migrationVersion, 165, 'Manifest version must match latest migration version (165)');

  const schema = fs.readFileSync(schemaPath, 'utf8');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS buildings'), 'Canonical schema.sql must define buildings');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS houses'), 'Canonical schema.sql must define houses');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_assets'), 'Canonical schema.sql must define V2 assets');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_accounts'), 'Canonical schema.sql must define V2 accounts');
  assert.ok(!schema.includes('character_lineage'), 'Canonical schema.sql must not include dropped character_lineage');
  assert.ok(!schema.includes('asset_ownership_events'), 'Canonical schema.sql must not include dropped asset_ownership_events');
  assert.ok(manifest.requiredTables.building_settlement_journals, 'Manifest must contain building_settlement_journals');
  assert.ok(manifest.requiredTables.human_technology_subscriptions, 'Manifest must contain human technology subscriptions');
  assert.ok(manifest.requiredTables.owner_registry.includes('economic_id'), 'Owner registry must expose compact economic IDs');
  assert.ok(manifest.requiredUniqueConstraints.some((key) => key.join(':') === 'owner_registry:economic_id'), 'Economic IDs must be unique');
  assert.ok(manifest.requiredTables.economic_assets, 'Manifest must contain the V2 asset catalog');
  assert.ok(manifest.requiredTables.economic_assets.includes('scale'), 'V2 assets must define fixed-point scale');
  assert.ok(manifest.requiredTables.economic_assets.includes('decimals'), 'V2 assets must define display precision');
  assert.ok(manifest.requiredTables.economic_accounts, 'Manifest must contain unified economic accounts');
  assert.ok(manifest.requiredTables.economic_transactions, 'Manifest must contain V2 transactions');
  assert.ok(manifest.requiredTables.economic_entries, 'Manifest must contain V2 entries');
  assert.ok(fs.readFileSync(path.resolve('db/migrations/154_economy_v2_idempotency.sql'), 'utf8').includes('ON CONFLICT (correlation_id) DO NOTHING'), 'V2 idempotency must be database-enforced');
  const posting = fs.readFileSync(path.resolve('db/migrations/155_economy_v2_posting_primitives.sql'), 'utf8');
  assert.match(posting, /CREATE OR REPLACE FUNCTION earth_post_transaction/);
  assert.match(posting, /CREATE OR REPLACE FUNCTION earth_post_settlement_batch/);
  assert.match(posting, /ORDER BY a\.id\s+FOR UPDATE/);
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_transactions'), 'Canonical schema.sql must define V2 transactions');
  assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS economic_entries'), 'Canonical schema.sql must define V2 entries');
  assert.ok(manifest.requiredIndexes.includes('economic_accounts_owner_asset_idx'), 'Manifest must contain the owner/asset account index');
  assert.ok(manifest.requiredTables.daily_settlement_profiles.includes('owner_economic_id'), 'Profiles must use compact economic owners');
  assert.ok(fs.readFileSync(path.resolve('db/migrations/156_economy_v2_bulk_settlement_profiles.sql'), 'utf8').includes('CREATE OR REPLACE FUNCTION earth_rebuild_dirty_profiles'), 'Profiles must have a bulk rebuild primitive');
  assert.ok(manifest.requiredTables.settlement_effects, 'Manifest must contain settlement effects');
  assert.ok(manifest.requiredTables.settlement_effect_nets, 'Manifest must contain phase-scoped effect nets');
  const nets = fs.readFileSync(path.resolve('db/migrations/158_economy_v2_phase_nets.sql'), 'utf8');
  assert.match(nets, /CREATE OR REPLACE FUNCTION earth_net_settlement_effects/);
  assert.match(nets, /WHERE e\.game_day = p_game_day/);
  const bulkPosting = fs.readFileSync(path.resolve('db/migrations/159_economy_v2_bulk_settlement_posting.sql'), 'utf8');
  assert.match(bulkPosting, /CREATE OR REPLACE FUNCTION earth_post_settlement_phase/);
  assert.match(bulkPosting, /SUM\(delta\)::BIGINT AS delta/);
  assert.match(bulkPosting, /UPDATE economic_accounts a/);
  assert.ok(manifest.requiredTables.daily_settlement_phase_runs.includes('lease_owner'), 'Settlement phases must track lease ownership');
  const phases = fs.readFileSync(path.resolve('db/migrations/160_economy_v2_resumable_settlement_phases.sql'), 'utf8');
  assert.match(phases, /CREATE OR REPLACE FUNCTION earth_claim_settlement_phase/);
  assert.match(phases, /CREATE OR REPLACE FUNCTION earth_complete_settlement_phase/);
  assert.ok(manifest.requiredTables.daily_settlement_runs.includes('shard_count'), 'Settlement runs must persist shard configuration');
  const shards = fs.readFileSync(path.resolve('db/migrations/161_economy_v2_shard_configuration.sql'), 'utf8');
  assert.match(shards, /CREATE OR REPLACE FUNCTION earth_settlement_shard/);
  assert.match(shards, /CREATE OR REPLACE FUNCTION earth_reduce_shared_settlement_effects/);
  assert.ok(manifest.requiredTables.economic_owner_totals, 'Manifest must contain cumulative economic totals');
  const totals = fs.readFileSync(path.resolve('db/migrations/162_economy_v2_owner_totals.sql'), 'utf8');
  assert.match(totals, /CREATE TRIGGER economic_entries_owner_totals/);
  assert.ok(manifest.requiredTables.settlement_rate_segments, 'Manifest must contain intraday rate segments');
  const rates = fs.readFileSync(path.resolve('db/migrations/163_economy_v2_rate_segments.sql'), 'utf8');
  assert.match(rates, /CREATE OR REPLACE FUNCTION earth_calculate_intraday_rate_units/);
  assert.match(rates, /LEAD\(minute\)/);
  const partitioning = fs.readFileSync(path.resolve('db/migrations/164_economy_v2_partition_entries.sql'), 'utf8');
  assert.match(partitioning, /PARTITION BY RANGE \(game_day\)/);
  assert.match(partitioning, /economic_entries_default/);
  assert.doesNotMatch(partitioning, /PARTITION BY RANGE.*economic_transactions/);
  const integrity = fs.readFileSync(path.resolve('db/migrations/165_economy_v2_integrity_checks.sql'), 'utf8');
  assert.match(integrity, /CREATE OR REPLACE FUNCTION earth_integrity_report/);
  assert.match(integrity, /economic_account_owner_missing/);
  assert.match(integrity, /CREATE OR REPLACE FUNCTION earth_validate_settlement_day/);
  const effects = fs.readFileSync(path.resolve('db/migrations/157_economy_v2_settlement_effects.sql'), 'utf8');
  assert.match(effects, /CREATE UNLOGGED TABLE IF NOT EXISTS settlement_effects/);
  assert.match(effects, /owner_economic_id BIGINT/);
  assert.ok(!manifest.requiredTables.businesses, 'Manifest must not contain the removed Business table');

  const functions = fs.readFileSync(functionsPath, 'utf8');
  assert.ok(functions.includes('CREATE OR REPLACE FUNCTION earth_transfer_credits'), 'functions.sql must contain earth_transfer_credits');

  const economyV2 = fs.readFileSync(path.resolve('db/migrations/150_economy_v2_compact_owner_ids.sql'), 'utf8');
  assert.match(economyV2, /ADD COLUMN IF NOT EXISTS economic_id BIGINT/);
  assert.match(economyV2, /owner_registry_economic_id_seq/);
  assert.match(economyV2, /owner_registry_economic_id_key/);
  assert.doesNotMatch(economyV2, /DROP TABLE/i, 'Plan 1 must not drop domain or legacy accounting tables');
  assert.doesNotMatch(economyV2, /ALTER TABLE (humans|cities|corporations)\s+.*DROP/i, 'Plan 1 must not rewrite domain IDs');
});
