-- EARTH D1 schema. SQLite-native version of the relational game baseline.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS humans (id TEXT PRIMARY KEY, account_id TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, age_years INTEGER NOT NULL DEFAULT 31, standing INTEGER NOT NULL DEFAULT 0, legacy INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS succession_plans (human_id TEXT PRIMARY KEY REFERENCES humans(id), successor_name TEXT NOT NULL, registered_game_day INTEGER NOT NULL, estate_period_days INTEGER NOT NULL DEFAULT 30);
CREATE TABLE IF NOT EXISTS institutions (id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK (kind IN ('OUC','CORPORATION','CITY','BUSINESS')), name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS ledger_entries (id TEXT PRIMARY KEY, game_day INTEGER NOT NULL, debit_account TEXT NOT NULL, credit_account TEXT NOT NULL, amount NUMERIC NOT NULL CHECK (amount > 0), currency TEXT NOT NULL DEFAULT 'CREDIT', reason_type TEXT NOT NULL, reason_id TEXT, rule_version TEXT NOT NULL DEFAULT 'v0.1', correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS market_orders (id TEXT PRIMARY KEY, human_id TEXT NOT NULL REFERENCES humans(id), product TEXT NOT NULL CHECK (product IN ('material','components','energy','compute')), quantity INTEGER NOT NULL CHECK (quantity > 0), limit_price NUMERIC NOT NULL CHECK (limit_price > 0), filled_quantity INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS market_trades (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES market_orders(id), product TEXT NOT NULL, quantity INTEGER NOT NULL CHECK (quantity > 0), clearing_price NUMERIC NOT NULL CHECK (clearing_price > 0), game_day INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS proposals (id TEXT PRIMARY KEY, institution_id TEXT NOT NULL REFERENCES institutions(id), title TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', opens_at TEXT NOT NULL, closes_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ballots (proposal_id TEXT NOT NULL REFERENCES proposals(id), human_id TEXT NOT NULL REFERENCES humans(id), choice TEXT NOT NULL CHECK (choice IN ('support','oppose','abstain')), weight NUMERIC NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (proposal_id, human_id));
CREATE TABLE IF NOT EXISTS technologies (id TEXT PRIMARY KEY, name TEXT NOT NULL, owner_id TEXT, progress NUMERIC NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1, metadata TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS world_state (id TEXT PRIMARY KEY, game_day INTEGER NOT NULL, game_minute INTEGER NOT NULL DEFAULT 0, health INTEGER NOT NULL DEFAULT 68, market_batch_seconds INTEGER NOT NULL DEFAULT 498);
CREATE TABLE IF NOT EXISTS businesses (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES humans(id), name TEXT NOT NULL, policy TEXT NOT NULL DEFAULT 'reliability', condition NUMERIC NOT NULL DEFAULT 100);
CREATE TABLE IF NOT EXISTS resource_balances (owner_id TEXT NOT NULL, resource TEXT NOT NULL CHECK (resource IN ('material','components','energy','compute')), amount NUMERIC NOT NULL DEFAULT 0, PRIMARY KEY (owner_id, resource));
CREATE TABLE IF NOT EXISTS communities (id TEXT PRIMARY KEY, name TEXT NOT NULL, founder_id TEXT NOT NULL REFERENCES humans(id), status TEXT NOT NULL DEFAULT 'active', shared_credits NUMERIC NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS cities (id TEXT PRIMARY KEY, institution_id TEXT NOT NULL UNIQUE REFERENCES institutions(id), residents INTEGER NOT NULL DEFAULT 0, housing_capacity INTEGER NOT NULL DEFAULT 0, energy_capacity INTEGER NOT NULL DEFAULT 0, connectivity_capacity INTEGER NOT NULL DEFAULT 0, health_capacity INTEGER NOT NULL DEFAULT 0, treasury NUMERIC NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS corporations (id TEXT PRIMARY KEY, institution_id TEXT NOT NULL UNIQUE REFERENCES institutions(id), member_count INTEGER NOT NULL DEFAULT 0, treasury NUMERIC NOT NULL DEFAULT 0, constitution_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS memberships (human_id TEXT PRIMARY KEY REFERENCES humans(id), corporation_id TEXT REFERENCES corporations(id), city_id TEXT REFERENCES cities(id), joined_game_day INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS budgets (id TEXT PRIMARY KEY, institution_id TEXT NOT NULL REFERENCES institutions(id), category TEXT NOT NULL, amount NUMERIC NOT NULL DEFAULT 0, game_day INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS machines (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES humans(id), name TEXT NOT NULL, machine_type TEXT NOT NULL, condition NUMERIC NOT NULL DEFAULT 100, utilization NUMERIC NOT NULL DEFAULT 0, maintenance_due INTEGER NOT NULL DEFAULT 0, productive_capacity NUMERIC NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS maintenance_events (id TEXT PRIMARY KEY, machine_id TEXT NOT NULL REFERENCES machines(id), owner_id TEXT NOT NULL REFERENCES humans(id), resource TEXT NOT NULL, amount NUMERIC NOT NULL CHECK (amount > 0), condition_before NUMERIC NOT NULL, condition_after NUMERIC NOT NULL, game_day INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS research_projects (id TEXT PRIMARY KEY, technology_id TEXT NOT NULL REFERENCES technologies(id), owner_id TEXT NOT NULL REFERENCES humans(id), budget NUMERIC NOT NULL DEFAULT 0, progress NUMERIC NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', started_game_day INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS patents (id TEXT PRIMARY KEY, technology_id TEXT NOT NULL REFERENCES technologies(id), owner_id TEXT NOT NULL REFERENCES humans(id), granted_game_day INTEGER NOT NULL, expiry_game_day INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS technology_licenses (id TEXT PRIMARY KEY, patent_id TEXT NOT NULL REFERENCES patents(id), licensor_id TEXT NOT NULL REFERENCES humans(id), licensee_id TEXT NOT NULL REFERENCES humans(id), royalty_rate NUMERIC NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS account_balances (account_id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, balance NUMERIC NOT NULL DEFAULT 0 CHECK (balance >= 0), currency TEXT NOT NULL DEFAULT 'CREDIT');
CREATE TABLE IF NOT EXISTS tax_rules (id TEXT PRIMARY KEY, scope TEXT NOT NULL, category TEXT NOT NULL, rate NUMERIC NOT NULL CHECK (rate >= 0 AND rate <= 1), active INTEGER NOT NULL DEFAULT 1, version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS ledger_game_day_idx ON ledger_entries(game_day);
CREATE INDEX IF NOT EXISTS market_orders_book_idx ON market_orders(product, status, limit_price, created_at);
