INSERT OR IGNORE INTO humans (id, account_id, display_name, age_years, standing, legacy) VALUES ('H-0044', 'account-amara', 'Amara Kline', 31, 742, 31);
INSERT OR IGNORE INTO institutions (id, kind, name) VALUES ('OUC-001', 'OUC', 'Organization of United Corporations'), ('CORP-001', 'CORPORATION', 'Helios Cooperative'), ('CITY-0084', 'CITY', 'New Carthage'), ('BUS-1048', 'BUSINESS', 'Kline Works');
INSERT OR IGNORE INTO technologies (id, name, owner_id, progress) VALUES ('TECH-001', 'Adaptive Maintenance AI', 'H-0044', 72);
INSERT OR IGNORE INTO world_state (id, game_day, game_minute, health, market_batch_seconds) VALUES ('WORLD', 184, 462, 68, 498);
INSERT OR IGNORE INTO businesses (id, owner_id, name, policy, condition) VALUES ('B-1048', 'H-0044', 'Kline Works', 'reliability', 96);
INSERT OR IGNORE INTO resource_balances (owner_id, resource, amount) VALUES ('H-0044', 'material', 420), ('H-0044', 'components', 86), ('H-0044', 'energy', 92), ('H-0044', 'compute', 64);
INSERT OR IGNORE INTO proposals (id, institution_id, title, body, status, opens_at, closes_at) VALUES ('042', 'OUC-001', 'Components maintenance levy', 'Fund resilient component maintenance across the shared economy.', 'open', CURRENT_TIMESTAMP, datetime('now', '+30 days'));
INSERT OR IGNORE INTO cities (id, institution_id, residents, housing_capacity, energy_capacity, connectivity_capacity, health_capacity, treasury) VALUES ('CITY-0084', 'CITY-0084', 18, 76, 92, 88, 64, 0);
INSERT OR IGNORE INTO corporations (id, institution_id, member_count, treasury, constitution_version) VALUES ('CORP-001', 'CORP-001', 42, 0, 1);
INSERT OR IGNORE INTO memberships (human_id, corporation_id, city_id, joined_game_day) VALUES ('H-0044', 'CORP-001', 'CITY-0084', 160);
INSERT OR IGNORE INTO budgets (id, institution_id, category, amount, game_day) VALUES ('BUDGET-CITY-0084', 'CITY-0084', 'public-services', 0, 184);
INSERT OR IGNORE INTO communities (id, name, founder_id, status, shared_credits) VALUES ('COMM-0001', 'Carthage Civic Mesh', 'H-0044', 'active', 0);
INSERT OR IGNORE INTO machines (id, owner_id, name, machine_type, condition, utilization, maintenance_due, productive_capacity) VALUES ('M-0044-01', 'H-0044', 'Service Robot 01', 'service-robot', 84, 62, 190, 1.2);
