version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript

  - package-ecosystem: pub
    directory: /flutter_client
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - flutter

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
