/** Canonical API contract.
 *
 * Route handlers remain free to use whatever internal implementation they
 * need, but every public endpoint has one owner and one authorization class.
 * Keep this list deliberately boring: it is also consumed by certification
 * tests and tooling that checks for accidental route duplication.
 */
export const API_ROUTE_OWNERS = [
  'AuthRoutes', 'SystemRoutes', 'HouseRoutes', 'BuildingRoutes',
  'ResearchRoutes', 'MarketRoutes', 'FinanceRoutes', 'InstitutionRoutes',
  'GovernanceRoutes', 'CommunityRoutes', 'ReadModelRoutes',
] as const;

export const API_AUTH_CLASSES = [
  'PUBLIC', 'AUTHENTICATED', 'HOUSE_SELF', 'HUMAN_SELF',
  'INSTITUTION_MEMBER', 'INSTITUTION_ROLE', 'INTERNAL_ADMIN',
] as const;

export type ApiRouteOwner = typeof API_ROUTE_OWNERS[number];
export type ApiAuthClass = typeof API_AUTH_CLASSES[number];
export type ApiRouteStatus = 'ACTIVE' | 'DEPRECATED' | 'REMOVED';

export type ApiRouteContract = {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  /** A normalized path. Dynamic identifiers use `{id}` or `{kind}`. */
  path: string;
  owner: ApiRouteOwner;
  auth: ApiAuthClass;
  service: string;
  status: ApiRouteStatus;
};

export const API_ROUTES: readonly ApiRouteContract[] = [
  { method: 'GET', path: '/api/live', owner: 'SystemRoutes', auth: 'PUBLIC', service: 'liveness', status: 'ACTIVE' },
  { method: 'GET', path: '/api/realtime', owner: 'SystemRoutes', auth: 'AUTHENTICATED', service: 'realtimeInvalidationBus', status: 'ACTIVE' },
  { method: 'GET', path: '/api/ready', owner: 'SystemRoutes', auth: 'PUBLIC', service: 'readiness', status: 'ACTIVE' },
  { method: 'GET', path: '/api/health', owner: 'SystemRoutes', auth: 'PUBLIC', service: 'health', status: 'ACTIVE' },
  { method: 'GET', path: '/internal/audit', owner: 'ReadModelRoutes', auth: 'INTERNAL_ADMIN', service: 'auditWorld', status: 'ACTIVE' },
  { method: 'GET', path: '/internal/v5/capacity-backfill/run', owner: 'ReadModelRoutes', auth: 'INTERNAL_ADMIN', service: 'getV5CapacityBackfillRun', status: 'ACTIVE' },
  { method: 'POST', path: '/internal/v5/capacity-backfill', owner: 'ReadModelRoutes', auth: 'INTERNAL_ADMIN', service: 'backfillV5CapacityBatch', status: 'ACTIVE' },
  { method: 'GET', path: '/internal/v5/cutover-readiness', owner: 'ReadModelRoutes', auth: 'INTERNAL_ADMIN', service: 'getV5CutoverReadiness', status: 'ACTIVE' },
  { method: 'GET', path: '/internal/v5/tax-reconciliation', owner: 'ReadModelRoutes', auth: 'INTERNAL_ADMIN', service: 'getV5TaxReconciliation', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/register', owner: 'AuthRoutes', auth: 'PUBLIC', service: 'registerAccount', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/login', owner: 'AuthRoutes', auth: 'PUBLIC', service: 'login', status: 'ACTIVE' },
  { method: 'GET', path: '/api/auth/verify-email', owner: 'AuthRoutes', auth: 'PUBLIC', service: 'verifyEmail', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/verify-email/resend', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'resendVerification', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/password-reset/request', owner: 'AuthRoutes', auth: 'PUBLIC', service: 'requestPasswordReset', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/password-reset/complete', owner: 'AuthRoutes', auth: 'PUBLIC', service: 'completePasswordReset', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/logout', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'logout', status: 'ACTIVE' },
  { method: 'GET', path: '/api/auth/me', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'getSessionAccount', status: 'ACTIVE' },
  { method: 'PATCH', path: '/api/auth/profile', owner: 'AuthRoutes', auth: 'HUMAN_SELF', service: 'updateProfile', status: 'ACTIVE' },
  { method: 'PATCH', path: '/api/life/testament', owner: 'AuthRoutes', auth: 'HUMAN_SELF', service: 'updateHumanTestament', status: 'ACTIVE' },
  { method: 'GET', path: '/api/auth/sessions', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'listSessions', status: 'ACTIVE' },
  { method: 'DELETE', path: '/api/auth/sessions/{id}', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'revokeSession', status: 'ACTIVE' },
  { method: 'DELETE', path: '/api/auth/sessions', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'revokeAllSessions', status: 'ACTIVE' },
  { method: 'DELETE', path: '/api/auth/account', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'deleteAccount', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/mfa/enroll', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'enrollMfa', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/mfa/confirm', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'confirmMfa', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/mfa/disable', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'disableMfa', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/rebirth', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'rebirth', status: 'ACTIVE' },
  { method: 'POST', path: '/api/auth/claim-heir', owner: 'AuthRoutes', auth: 'AUTHENTICATED', service: 'claimHeir', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'getHouseProfile', status: 'ACTIVE' },
  { method: 'PATCH', path: '/api/house/profile', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'updateHouseProfile', status: 'ACTIVE' },
  { method: 'POST', path: '/api/house/succession', owner: 'HouseRoutes', auth: 'HUMAN_SELF', service: 'registerHouseSuccessor', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/daily-summary', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'getHouseDailySummary', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/onboarding', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'getHouseOnboarding', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/residency', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'getHouseResidency', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/residency/quote', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'quoteHouseMove', status: 'RETIRED' },
  { method: 'POST', path: '/api/house/residency/move', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'moveHouseResidence', status: 'RETIRED' },
  { method: 'POST', path: '/api/house/onboarding/advance', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'advanceHouseOnboarding', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/entry-opportunities', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'getHouseEntrySupport', status: 'ACTIVE' },
  { method: 'POST', path: '/api/house/entry-support/claim', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'claimHouseEntrySupport', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/catch-up-targets', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'getHouseCatchUpTargets', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/policies', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'listHousePolicies', status: 'DEPRECATED' },
  { method: 'POST', path: '/api/house/policies', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'saveHousePolicy', status: 'DEPRECATED' },
  { method: 'PUT', path: '/api/house/automation', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'saveHouseAutomation', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/automation', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'getHouseAutomation', status: 'ACTIVE' },
  { method: 'POST', path: '/api/house/automation/preview', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'previewHouseAutomation', status: 'ACTIVE' },
  { method: 'GET', path: '/api/command-center', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'getDecisionQueue', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/command/overview', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'getV5Overview', status: 'ACTIVE' },
  { method: 'GET', path: '/api/decisions', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'getDecisionQueue', status: 'ACTIVE' },
  { method: 'POST', path: '/api/house/{action}', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'houseService', status: 'ACTIVE' },
  { method: 'GET', path: '/api/house/{action}', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'houseReadModel', status: 'ACTIVE' },
  { method: 'POST', path: '/api/house/{action}/{subaction}', owner: 'HouseRoutes', auth: 'HOUSE_SELF', service: 'houseService', status: 'ACTIVE' },
  { method: 'GET', path: '/api/buildings/catalog', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'buildingCatalog', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/buildings', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'purchaseV5Building', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/buildings/quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteV5Building', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/buildings/{id}/upgrade', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'upgradeBuilding', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/buildings/{id}/upgrade-quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingUpgrade', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/buildings/{id}/retrofit-quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingRetrofit', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/buildings/{id}/policy', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'setBuildingOperatingMode', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/buildings/{id}/policy-quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingOperatingMode', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/buildings/{id}/demolish', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'decommissionBuilding', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/buildings/{id}/demolition-quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingDemolition', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/buildings/{id}/capital-options', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'getBuildingCapitalOptions', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/buildings/{id}/capital-projects', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'startBuildingCapitalProject', status: 'ACTIVE' },
  { method: 'GET', path: '/api/events', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'listGameEvents', status: 'ACTIVE' },
  { method: 'GET', path: '/api/news', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'listNews', status: 'ACTIVE' },
  { method: 'GET', path: '/api/history', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'listHistory', status: 'ACTIVE' },
  { method: 'GET', path: '/api/notifications', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'listNotifications', status: 'ACTIVE' },
  { method: 'POST', path: '/api/notifications/read-all', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'markAllNotificationsRead', status: 'ACTIVE' },
  { method: 'POST', path: '/api/notifications/{id}/read', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'markNotificationRead', status: 'ACTIVE' },
  { method: 'GET', path: '/api/rankings', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'listRankings', status: 'ACTIVE' },
  { method: 'GET', path: '/api/pantheon', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'listPantheonCompatibility', status: 'DEPRECATED' },
  { method: 'GET', path: '/api/memorial', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'listMemorialArchive', status: 'ACTIVE' },
  { method: 'GET', path: '/api/memorial/citizens/{id}', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'getMemorialCitizenBiography', status: 'ACTIVE' },
  { method: 'GET', path: '/api/memorial/houses/{id}/lineage', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'getMemorialHouseLineage', status: 'ACTIVE' },
  { method: 'GET', path: '/api/world/conditions', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'listWorldConditions', status: 'ACTIVE' },
  { method: 'GET', path: '/api/cemetery', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'listCemeteryCompatibility', status: 'DEPRECATED' },
  { method: 'GET', path: '/api/institutions', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'listInstitutions', status: 'ACTIVE' },
  { method: 'GET', path: '/api/services/status', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'serviceProjection', status: 'ACTIVE' },
  { method: 'GET', path: '/api/market/history', owner: 'ReadModelRoutes', auth: 'PUBLIC', service: 'marketPriceHistory', status: 'DEPRECATED' },
  { method: 'GET', path: '/api/mutual-credit/networks', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'listMutualCreditNetworks', status: 'ACTIVE' },
  { method: 'POST', path: '/api/mutual-credit/networks', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'createMutualCreditNetwork', status: 'ACTIVE' },
  { method: 'GET', path: '/api/mutual-credit/networks/{id}', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'getMutualCreditNetwork', status: 'ACTIVE' },
  { method: 'POST', path: '/api/mutual-credit/networks/{id}/join', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'joinMutualCreditNetwork', status: 'ACTIVE' },
  { method: 'POST', path: '/api/mutual-credit/networks/{id}/transfers', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'transferMutualCredit', status: 'ACTIVE' },
  { method: 'POST', path: '/api/mutual-credit/networks/{id}/guarantees', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'addMutualCreditGuarantee', status: 'ACTIVE' },
  { method: 'POST', path: '/api/real-estate/purchase', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'purchaseBuilding', status: 'REMOVED' },
  { method: 'GET', path: '/api/real-estate/projects', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'listConstructionProjects', status: 'ACTIVE' },
  { method: 'GET', path: '/api/real-estate/buildings/{id}/capital-options', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'getBuildingCapitalOptions', status: 'RETIRED' },
  { method: 'POST', path: '/api/real-estate/buildings/{id}/capital-projects', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'startBuildingCapitalProject', status: 'RETIRED' },
  { method: 'POST', path: '/api/real-estate/upgrade', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'upgradeBuilding', status: 'RETIRED' },
  { method: 'GET', path: '/api/real-estate/buildings/{id}/upgrade-quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingUpgrade', status: 'RETIRED' },
  { method: 'POST', path: '/api/real-estate/policy', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'setBuildingOperatingMode', status: 'RETIRED' },
  { method: 'GET', path: '/api/real-estate/buildings/{id}/policy-quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingOperatingMode', status: 'RETIRED' },
  { method: 'POST', path: '/api/real-estate/demolish', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'decommissionBuilding', status: 'RETIRED' },
  { method: 'GET', path: '/api/real-estate/buildings/{id}/demolition-quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingDemolition', status: 'RETIRED' },
  { method: 'POST', path: '/api/real-estate/projects/{id}/cancel', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'cancelConstructionProject', status: 'ACTIVE' },
  { method: 'GET', path: '/api/real-estate/quote', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'constructionQuote', status: 'REMOVED' },
  { method: 'POST', path: '/api/real-estate/{action}', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'buildingService', status: 'ACTIVE' },
  { method: 'GET', path: '/api/market/instruments', owner: 'MarketRoutes', auth: 'PUBLIC', service: 'listInstruments', status: 'ACTIVE' },
  { method: 'GET', path: '/api/market/{instrument}/{view}', owner: 'MarketRoutes', auth: 'PUBLIC', service: 'marketReadModel', status: 'ACTIVE' },
  { method: 'GET', path: '/api/market/orders/my', owner: 'MarketRoutes', auth: 'HOUSE_SELF', service: 'listOrders', status: 'ACTIVE' },
  { method: 'GET', path: '/api/market/positions', owner: 'MarketRoutes', auth: 'HOUSE_SELF', service: 'houseCommodityPositions', status: 'ACTIVE' },
  { method: 'POST', path: '/api/market/order-quote', owner: 'MarketRoutes', auth: 'HOUSE_SELF', service: 'quoteOrder', status: 'ACTIVE' },
  { method: 'POST', path: '/api/market/orders', owner: 'MarketRoutes', auth: 'HOUSE_SELF', service: 'submitOrder', status: 'ACTIVE' },
  { method: 'DELETE', path: '/api/market/orders/{id}', owner: 'MarketRoutes', auth: 'HOUSE_SELF', service: 'cancelOrder', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/overview', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'getHouseFinanceOverview', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/me', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'getHouseFinanceOverview', status: 'DEPRECATED' },
  { method: 'GET', path: '/api/finance/personal', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'getHouseFinanceOverview', status: 'DEPRECATED' },
  { method: 'GET', path: '/api/finance/tax-statement', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'getTaxStatement', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/quote', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'authoritativeFinancialQuote', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/projection', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'ledgerFinancialProjection', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/{view}', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'financeReadModel', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/corporations/{id}', owner: 'FinanceRoutes', auth: 'INSTITUTION_MEMBER', service: 'getCorporationFiscalState', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/corporations/directory', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'listCorporations', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/corporations/{id}/profile', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'getCorporationProfile', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/corporations/{id}/roles', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'getCorporationRoles', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/roles/appoint', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'appointCorporationRole', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/roles/remove', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'removeCorporationRole', status: 'ACTIVE' },
  { method: 'GET', path: '/api/corporations', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'listCorporations', status: 'RETIRED' },
  { method: 'POST', path: '/api/corporations', owner: 'InstitutionRoutes', auth: 'HUMAN_SELF', service: 'createCorporation', status: 'RETIRED' },
  { method: 'GET', path: '/api/corporations/{id}/territories', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'listCorporationTerritories', status: 'ACTIVE' },
  { method: 'GET', path: '/api/territories/{id}/capacity', owner: 'BuildingRoutes', auth: 'AUTHENTICATED', service: 'getTerritoryCapacity', status: 'ACTIVE' },
  { method: 'GET', path: '/api/territories/{id}/rights', owner: 'BuildingRoutes', auth: 'AUTHENTICATED', service: 'listTerritoryRights', status: 'RETIRED' },
  { method: 'GET', path: '/api/territories/{id}/commons', owner: 'BuildingRoutes', auth: 'AUTHENTICATED', service: 'getCommonsStatement', status: 'RETIRED' },
  { method: 'GET', path: '/api/v5/house/capacity', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'getV5HouseCapacity', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/capacity', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'getV5EarthCapacity', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/corporations/{id}/capacity', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'getV5CorporationCapacity', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/corporations/{id}/membership', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'quoteV5CorporationMembership', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/membership', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'applyV5CorporationMembership', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/membership/leave', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'leaveV5Corporation', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/founding/quote', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'quoteV5CorporationFounding', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'foundV5Corporation', status: 'ACTIVE' },
  { method: 'PATCH', path: '/api/v5/corporations/{id}/membership/applications/{id}', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'decideV5MembershipApplication', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/corporations/{id}/membership/applications', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'listV5MembershipApplications', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/v5/proposals', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'createV5GovernanceProposal', status: 'ACTIVE' },
  { method: 'GET', path: '/api/governance/v5/proposals', owner: 'GovernanceRoutes', auth: 'HOUSE_SELF', service: 'listV5GovernanceProposals', status: 'ACTIVE' },
  { method: 'GET', path: '/api/governance/v5/constitution', owner: 'GovernanceRoutes', auth: 'HOUSE_SELF', service: 'getConstitutionReadModel', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/v5/constitution/preview', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'previewConstitutionAmendment', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/v5/proposals/{id}/vote', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'castV5GovernanceVote', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/v5/proposals/{id}/resolve', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'resolveV5GovernanceProposal', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/house/capacity-resolution', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'listV5CapacityResolutionCases', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/house/capacity-resolution', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'openV5CapacityResolutionCase', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/house/capacity-resolution/{id}/liquidate/{id}', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'liquidateV5HouseBuilding', status: 'ACTIVE' },
  { method: 'GET', path: '/api/v5/corporations/{id}/receivership', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'listV5CorporationReceivershipCases', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/receivership/{id}/restructure', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'submitV5CorporationRestructuringPlan', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/invites', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'issueV5CorporationInvite', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/leadership/delegate', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'delegateV5CorporationLeadership', status: 'ACTIVE' },
  { method: 'POST', path: '/api/v5/corporations/{id}/dissolution/schedule', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'scheduleV5CorporationDissolution', status: 'ACTIVE' },
  { method: 'POST', path: '/api/territories/{id}/commons', owner: 'BuildingRoutes', auth: 'INSTITUTION_ROLE', service: 'declareCommonsDividend', status: 'RETIRED' },
  { method: 'GET', path: '/api/real-estate/rights', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'listTerritoryRights', status: 'RETIRED' },
  { method: 'POST', path: '/api/real-estate/rights', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'acquireTerritoryRight', status: 'RETIRED' },
  { method: 'POST', path: '/api/real-estate/rights/{id}/release', owner: 'BuildingRoutes', auth: 'HOUSE_SELF', service: 'releaseTerritoryRight', status: 'RETIRED' },
  { method: 'POST', path: '/api/corporations/{id}/admission-policy', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'setCorporationAdmissionPolicy', status: 'RETIRED' },
  { method: 'POST', path: '/api/corporations/{id}/membership', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'joinCorporation', status: 'RETIRED' },
  { method: 'DELETE', path: '/api/corporations/{id}/membership', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'leaveCorporation', status: 'RETIRED' },
  { method: 'POST', path: '/api/corporations/{id}/contributions', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'contributeCorporation', status: 'ACTIVE' },
  { method: 'POST', path: '/api/corporations/{id}/tax-charter', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'setCorporationTaxCharter', status: 'RETIRED' },
  { method: 'POST', path: '/api/corporations/{id}/treasury/spend', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'spendCorporationTreasury', status: 'ACTIVE' },
  { method: 'GET', path: '/api/institutions/{id}/budget/{view}', owner: 'InstitutionRoutes', auth: 'INSTITUTION_MEMBER', service: 'budgetReadModel', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'listOrganizations', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/charters/templates', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'listCharterTemplates', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'createOrganization', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/membership', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'joinOrganization', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/charter', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'getOrganizationCharter', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/authority', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'listOrganizationAuthority', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/offices/{office}/appoint', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'appointOrganizationOffice', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/offices/{office}/resign', owner: 'InstitutionRoutes', auth: 'HUMAN_SELF', service: 'resignOrganizationOffice', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/assets/{assetId}/ownership', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'getAssetOwnership', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/assets/{assetId}/ownership', owner: 'InstitutionRoutes', auth: 'HOUSE_SELF', service: 'subscribeToAssetOwnership', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/assets/{assetId}/distributions', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'distributeOwnership', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/contracts', owner: 'InstitutionRoutes', auth: 'INSTITUTION_MEMBER', service: 'listOrganizationContracts', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'createOrganizationContract', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts/{contractId}/sign', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'signOrganizationContract', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/contracts/performance', owner: 'InstitutionRoutes', auth: 'INSTITUTION_MEMBER', service: 'listContractPerformance', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts/performance/{performanceId}/dispute', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'disputeContractPerformance', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts/performance/{performanceId}/deliver', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'submitContractDelivery', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts/performance/{performanceId}/accept', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'acceptContractDelivery', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts/performance/{performanceId}/reject', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'rejectContractDelivery', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts/performance/{performanceId}/resolve', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'resolveContractDispute', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/contracts/performance/{performanceId}/{action}', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'contractPerformanceAction', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/charter/history', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'getOrganizationCharterHistory', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/charter/validate', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'validateOrganizationCharter', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/charter/amend', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'amendOrganizationCharter', status: 'RETIRED' },
  { method: 'GET', path: '/api/organizations/{id}/finance', owner: 'InstitutionRoutes', auth: 'INSTITUTION_MEMBER', service: 'getOrganizationFinance', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/technology-adoptions', owner: 'InstitutionRoutes', auth: 'INSTITUTION_MEMBER', service: 'legacyOrganizationTechnologyAdoptions', status: 'RETIRED' },
  { method: 'POST', path: '/api/organizations/{id}/technology-adoptions', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'legacyOrganizationTechnologyAdoption', status: 'RETIRED' },
  { method: 'POST', path: '/api/organizations/{id}/technology-adoptions/propose', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'legacyOrganizationTechnologyProposal', status: 'RETIRED' },
  { method: 'POST', path: '/api/organizations/{id}/technology-adoptions/{adoptionId}/retire', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'legacyOrganizationTechnologyRetirement', status: 'RETIRED' },
  { method: 'POST', path: '/api/organizations/{id}/finance/provision', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'provisionOrganizationEconomy', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/finance/spend', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'spendOrganizationBudget', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/members', owner: 'InstitutionRoutes', auth: 'AUTHENTICATED', service: 'listOrganizationMembers', status: 'ACTIVE' },
  { method: 'GET', path: '/api/organizations/{id}/requests', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'listOrganizationRequests', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/requests/{requestId}/approve', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'approveOrganizationRequest', status: 'ACTIVE' },
  { method: 'POST', path: '/api/organizations/{id}/requests/{requestId}/reject', owner: 'InstitutionRoutes', auth: 'INSTITUTION_ROLE', service: 'rejectOrganizationRequest', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/proposals', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'createProposal', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/v4/proposals', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'createGovernanceProposalV4', status: 'ACTIVE' },
  { method: 'GET', path: '/api/governance/v4/organizations/{id}/method', owner: 'GovernanceRoutes', auth: 'AUTHENTICATED', service: 'getOrganizationVotingSettings', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/v4/organizations/{id}/method', owner: 'GovernanceRoutes', auth: 'INSTITUTION_ROLE', service: 'setOrganizationVotingSettings', status: 'RETIRED' },
  { method: 'POST', path: '/api/governance/v4/proposals/{id}/vote', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'castGovernanceVoteV4', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/v4/proposals/{id}/resolve', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'resolveGovernanceProposalV4', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/rules', owner: 'GovernanceRoutes', auth: 'INSTITUTION_ROLE', service: 'amendRules', status: 'RETIRED' },
  { method: 'GET', path: '/api/governance/rules', owner: 'GovernanceRoutes', auth: 'AUTHENTICATED', service: 'getConstitutionReadModel', status: 'ACTIVE' },
  { method: 'GET', path: '/api/governance/{view}', owner: 'GovernanceRoutes', auth: 'AUTHENTICATED', service: 'governanceReadModel', status: 'ACTIVE' },
  { method: 'GET', path: '/api/research/{view}', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'researchReadModel', status: 'ACTIVE' },
  { method: 'POST', path: '/api/research/{action}', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'researchService', status: 'ACTIVE' },
  { method: 'GET', path: '/api/research/buildings', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'listBuildingResearch', status: 'ACTIVE' },
  { method: 'POST', path: '/api/research/buildings', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'startBuildingResearch', status: 'ACTIVE' },
  { method: 'POST', path: '/api/research/buildings/quote', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'quoteBuildingResearch', status: 'ACTIVE' },
  { method: 'POST', path: '/api/research/contribute', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'contributeResearch', status: 'ACTIVE' },
  { method: 'GET', path: '/api/communities', owner: 'CommunityRoutes', auth: 'AUTHENTICATED', service: 'listCommunities', status: 'ACTIVE' },
  { method: 'POST', path: '/api/communities', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'createCommunity', status: 'ACTIVE' },
  { method: 'GET', path: '/api/communities/{id}', owner: 'CommunityRoutes', auth: 'AUTHENTICATED', service: 'communityReadModel', status: 'ACTIVE' },
  { method: 'PATCH', path: '/api/communities/{id}', owner: 'CommunityRoutes', auth: 'INSTITUTION_ROLE', service: 'updateCommunity', status: 'ACTIVE' },
  { method: 'DELETE', path: '/api/communities/{id}', owner: 'CommunityRoutes', auth: 'INSTITUTION_ROLE', service: 'disbandCommunity', status: 'ACTIVE' },
  { method: 'GET', path: '/api/communities/{id}/members', owner: 'CommunityRoutes', auth: 'AUTHENTICATED', service: 'listCommunityMembers', status: 'ACTIVE' },
  { method: 'POST', path: '/api/communities/{id}/join', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'joinCommunity', status: 'ACTIVE' },
  { method: 'POST', path: '/api/communities/{id}/leave', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'leaveCommunity', status: 'ACTIVE' },
  { method: 'PATCH', path: '/api/communities/{id}/members/{houseId}', owner: 'CommunityRoutes', auth: 'INSTITUTION_ROLE', service: 'setCommunityMemberRole', status: 'ACTIVE' },
  { method: 'DELETE', path: '/api/communities/{id}/members/{houseId}', owner: 'CommunityRoutes', auth: 'INSTITUTION_ROLE', service: 'removeCommunityMember', status: 'ACTIVE' },
  { method: 'GET', path: '/api/communities/{id}/requests', owner: 'CommunityRoutes', auth: 'INSTITUTION_ROLE', service: 'listCommunityRequests', status: 'ACTIVE' },
  { method: 'POST', path: '/api/communities/{id}/requests/{requestId}/approve', owner: 'CommunityRoutes', auth: 'INSTITUTION_ROLE', service: 'approveCommunityRequest', status: 'ACTIVE' },
  { method: 'POST', path: '/api/communities/{id}/requests/{requestId}/reject', owner: 'CommunityRoutes', auth: 'INSTITUTION_ROLE', service: 'rejectCommunityRequest', status: 'ACTIVE' },
  { method: 'GET', path: '/api/world', owner: 'SystemRoutes', auth: 'AUTHENTICATED', service: 'worldSnapshot', status: 'ACTIVE' },
  { method: 'GET', path: '/api/world/activity', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'worldActivity', status: 'ACTIVE' },
  { method: 'GET', path: '/api/earth/programs', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'listGlobalPrograms', status: 'ACTIVE' },
  { method: 'GET', path: '/api/initiatives', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'listInitiatives', status: 'ACTIVE' },
  { method: 'POST', path: '/api/initiatives/{id}/contributions', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'contributeToInitiative', status: 'ACTIVE' },
  { method: 'POST', path: '/api/initiatives/{id}/contribution-quote', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'quoteInitiativeContribution', status: 'ACTIVE' },
  { method: 'POST', path: '/api/earth/programs', owner: 'ReadModelRoutes', auth: 'NONE', service: 'createGlobalProgram', status: 'RETIRED' },
  { method: 'GET', path: '/api/earth/technology/generations', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'getTechnologyGenerations', status: 'ACTIVE' },
  { method: 'GET', path: '/api/earth/technology/frontier', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'getEarthTechnologyFrontier', status: 'ACTIVE' },
  { method: 'GET', path: '/api/public-projects', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'listPublicProjects', status: 'ACTIVE' },
  { method: 'POST', path: '/api/public-projects', owner: 'ReadModelRoutes', auth: 'NONE', service: 'createPublicProject', status: 'RETIRED' },
  { method: 'GET', path: '/api/public-projects/{id}', owner: 'ReadModelRoutes', auth: 'AUTHENTICATED', service: 'getPublicProject', status: 'ACTIVE' },
  { method: 'POST', path: '/api/public-projects/{id}/contributions', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'contributeToPublicProject', status: 'ACTIVE' },
  { method: 'POST', path: '/api/public-projects/{id}/matching-fund', owner: 'ReadModelRoutes', auth: 'NONE', service: 'fundMatchingPool', status: 'RETIRED' },
  { method: 'POST', path: '/api/public-projects/{id}/settle', owner: 'ReadModelRoutes', auth: 'NONE', service: 'settlePublicProject', status: 'RETIRED' },
  { method: 'POST', path: '/api/earth/programs/{id}/fund', owner: 'ReadModelRoutes', auth: 'NONE', service: 'fundGlobalProgram', status: 'RETIRED' },
  { method: 'POST', path: '/api/earth/programs/{id}/contributions', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'contributeToGlobalProgram', status: 'ACTIVE' },
  { method: 'GET', path: '/api/earth/programs/{id}/contributions', owner: 'ReadModelRoutes', auth: 'HOUSE_SELF', service: 'listGlobalProgramContributions', status: 'ACTIVE' },
  { method: 'POST', path: '/api/earth/programs/{id}/settle', owner: 'ReadModelRoutes', auth: 'NONE', service: 'settleGlobalProgramFunding', status: 'RETIRED' },
  { method: 'GET', path: '/api/technology', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'technologyCatalog', status: 'ACTIVE' },
  { method: 'POST', path: '/api/technology/projects', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'createResearchProject', status: 'ACTIVE' },
  { method: 'POST', path: '/api/technology/projects/quote', owner: 'ResearchRoutes', auth: 'HOUSE_SELF', service: 'quoteResearchProject', status: 'ACTIVE' },
  { method: 'GET', path: '/api/life/{view}', owner: 'HouseRoutes', auth: 'HUMAN_SELF', service: 'lifeReadModel', status: 'ACTIVE' },
  { method: 'POST', path: '/api/life/successor', owner: 'HouseRoutes', auth: 'HUMAN_SELF', service: 'registerSuccessor', status: 'ACTIVE' },
  { method: 'GET', path: '/api/economy/{view}', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'economyReadModel', status: 'ACTIVE' },
  { method: 'GET', path: '/api/economy/resources', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'houseResourceAnalytics', status: 'ACTIVE' },
  { method: 'GET', path: '/api/economy/resources/metadata', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'resourceBehaviorMetadata', status: 'ACTIVE' },
  { method: 'GET', path: '/api/economy/resources/global', owner: 'FinanceRoutes', auth: 'AUTHENTICATED', service: 'globalResourceAnalytics', status: 'ACTIVE' },
  { method: 'POST', path: '/api/telemetry/error', owner: 'SystemRoutes', auth: 'AUTHENTICATED', service: 'logClientError', status: 'ACTIVE' },
  { method: 'GET', path: '/api/comm/channels', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'listChannels', status: 'ACTIVE' },
  { method: 'GET', path: '/api/comm/messages', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'listMessages', status: 'ACTIVE' },
  { method: 'POST', path: '/api/comm/messages', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'sendMessage', status: 'ACTIVE' },
  { method: 'POST', path: '/api/comm/direct', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'openDirectConversation', status: 'ACTIVE' },
  { method: 'GET', path: '/api/comm/metrics', owner: 'CommunityRoutes', auth: 'HOUSE_SELF', service: 'communicationsMetrics', status: 'ACTIVE' },
  { method: 'POST', path: '/api/governance/proposals/{id}/vote', owner: 'GovernanceRoutes', auth: 'HUMAN_SELF', service: 'castBallot', status: 'ACTIVE' },
  { method: 'POST', path: '/api/finance/recover', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'recoverFinance', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/bank/deposits', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'listBankDeposits', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/bank/deposit-quote', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'getBankDepositQuote', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/bank/loans', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'listBankLoans', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/bank/loan-quote', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'getBankLoanQuote', status: 'ACTIVE' },
  { method: 'POST', path: '/api/finance/bank/loan', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'originateBankLoan', status: 'ACTIVE' },
  { method: 'POST', path: '/api/finance/bank/loan/{id}/repay', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'repayBankLoan', status: 'ACTIVE' },
  { method: 'POST', path: '/api/finance/bank/loan/{id}/guarantee', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'addBankLoanGuarantee', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/bank/risk', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'getBankRiskProjection', status: 'ACTIVE' },
  { method: 'GET', path: '/api/finance/organizations/{id}/risk', owner: 'FinanceRoutes', auth: 'INSTITUTION_MEMBER', service: 'getOrganizationFinancialState', status: 'ACTIVE' },
  { method: 'POST', path: '/api/finance/organizations/{id}/resolution', owner: 'FinanceRoutes', auth: 'INSTITUTION_ROLE', service: 'createOrganizationResolutionCase', status: 'ACTIVE' },
  { method: 'POST', path: '/api/finance/bank/deposit', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'createBankDeposit', status: 'ACTIVE' },
  { method: 'POST', path: '/api/finance/bank/withdraw', owner: 'FinanceRoutes', auth: 'HOUSE_SELF', service: 'withdrawBankDeposit', status: 'ACTIVE' },
];

export function routeKey(route: Pick<ApiRouteContract, 'method' | 'path'>): string {
  return `${route.method} ${route.path}`;
}

export function validateApiRegistry(routes: readonly ApiRouteContract[] = API_ROUTES): string[] {
  const failures: string[] = [];
  const keys = new Set<string>();
  for (const route of routes) {
    const key = routeKey(route);
    if (keys.has(key)) failures.push(`duplicate route ${key}`);
    keys.add(key);
    if (!API_ROUTE_OWNERS.includes(route.owner)) failures.push(`${key} has unknown owner ${route.owner}`);
    if (!API_AUTH_CLASSES.includes(route.auth)) failures.push(`${key} has unknown auth class ${route.auth}`);
    if (!route.service?.trim()) failures.push(`${key} has no service`);
    if (!route.status) failures.push(`${key} has no status`);
  }
  return failures;
}
