import type { PostgresRepository } from './repository.ts';
import { assessBuildingAge } from './building-age.ts';

export async function getBuildingCapitalOptions(repository: PostgresRepository, buildingId: string): Promise<Record<string, unknown>> {
  const day = Number((await repository.query<{ game_day: string }>("SELECT game_day::TEXT FROM world_state WHERE id = 'WORLD'")).rows[0]?.game_day ?? 1);
  const row = (await repository.query<any>(`SELECT b.id, b.catalog_id, b.started_game_day, COALESCE(b.last_major_rebuild_game_day, b.started_game_day) AS last_major_rebuild_game_day, c.code, r.design_life_days, r.overdue_burden_bps_per_day, r.maximum_burden_bps, COALESCE(jsonb_agg(jsonb_build_object('domainId', i.domain_id, 'generationId', i.generation_id, 'installedGameDay', i.installed_game_day)) FILTER (WHERE i.id IS NOT NULL), '[]'::jsonb) AS installed_generations FROM buildings b JOIN building_catalog c ON c.id = b.catalog_id JOIN building_design_life_rules r ON r.catalog_id = b.catalog_id LEFT JOIN building_generation_installations i ON i.building_id = b.id AND i.status = 'ACTIVE' WHERE b.id = $1 GROUP BY b.id, c.code, r.design_life_days, r.overdue_burden_bps_per_day, r.maximum_burden_bps`, [buildingId])).rows[0];
  if (!row) throw new Error('Building not found');
  const age = assessBuildingAge({ currentGameDay: BigInt(day), lastMajorRebuildGameDay: BigInt(row.last_major_rebuild_game_day), designLifeDays: BigInt(row.design_life_days), overdueBurdenBpsPerDay: BigInt(row.overdue_burden_bps_per_day), maximumBurdenBps: BigInt(row.maximum_burden_bps) });
  return { building: { id: row.id, code: row.code, ageDays: age.ageDays.toString(), designLifeDays: age.designLifeDays.toString(), overdueDays: age.overdueDays.toString(), burdenMultiplierBps: age.burdenMultiplierBps.toString(), operable: age.operable, installedGenerations: row.installed_generations }, options: [{ type: 'CONTINUE', effect: 'retain_current_age' }, { type: 'OVERHAUL', effect: 'reset_major_rebuild_day' }, { type: 'TIER_UPGRADE', effect: 'replace_physical_scale' }, { type: 'GENERATION_RETROFIT', effect: 'install_generation_without_resetting_age' }], generatedFrom: 'postgres-canonical-facts' };
}
