export type MachineCatalogEntry = {
  name: string;
  category: 'energy' | 'food' | 'extraction' | 'components' | 'compute' | 'specialized';
  tier: 1 | 2 | 3 | 4;
  output: string;
  inputResource: string;
  inputPerOutput: number;
  credit: number;
  material: number;
  capacity: number;
  baseDegradationRate: number;
  description: string;
  requiredTech?: string;
};

/**
 * Authoritative production and mining asset catalog for Earth.
 * Features 24 distinct industrial, mining, energy, agricultural, manufacturing,
 * robotic, compute, and orbital assets across 4 capability tiers.
 */
export const MACHINE_CATALOG: Record<string, MachineCatalogEntry> = {
  // --- ENERGY (Power Generation) ---
  'solar-photovoltaic-array': {
    name: 'Solar Photovoltaic Array',
    category: 'energy',
    tier: 1,
    output: 'energy',
    inputResource: 'material',
    inputPerOutput: 0.05,
    credit: 3200,
    material: 50,
    capacity: 1.5,
    baseDegradationRate: 0.8,
    description: 'Terrestrial photovoltaic solar panel field converting planetary solar flux into clean electrical power.',
  },
  'geothermal-tap': {
    name: 'Geothermal Deep Tap',
    category: 'energy',
    tier: 2,
    output: 'energy',
    inputResource: 'material',
    inputPerOutput: 0.1,
    credit: 6800,
    material: 110,
    capacity: 2.2,
    baseDegradationRate: 1.0,
    description: 'Pressurized deep-bore thermal exchange well tapping mantle heat for continuous high-stability base-load power.',
  },
  'fusion-tokamak-rig': {
    name: 'Magnetic Fusion Dynamo',
    category: 'energy',
    tier: 3,
    output: 'energy',
    inputResource: 'components',
    inputPerOutput: 0.15,
    credit: 14500,
    material: 220,
    capacity: 3.5,
    baseDegradationRate: 1.2,
    description: 'Deuterium-tritium magnetic confinement tokamak generating massive high-density megawatt output.',
  },
  'orbital-solar-collector': {
    name: 'Orbital Microwave Beam Array',
    category: 'energy',
    tier: 4,
    output: 'energy',
    inputResource: 'components',
    inputPerOutput: 0.2,
    credit: 32000,
    material: 450,
    capacity: 5.0,
    baseDegradationRate: 1.4,
    description: 'Geosynchronous orbital satellite swarm beaming constant unfiltered solar power via phased microwave rectennas.',
    requiredTech: 'Orbital Logistics',
  },

  // --- FOOD & BIOMASS ---
  'hydroponic-tower': {
    name: 'Vertical Hydroponic Tower',
    category: 'food',
    tier: 1,
    output: 'food',
    inputResource: 'energy',
    inputPerOutput: 0.3,
    credit: 3400,
    material: 55,
    capacity: 1.4,
    baseDegradationRate: 0.9,
    description: 'Automated vertical aeroponic cultivation tower growing nutrient-dense crops under optimized LED spectrums.',
  },
  'algae-photobioreactor': {
    name: 'Micro-Algae Bio-Vat',
    category: 'food',
    tier: 2,
    output: 'food',
    inputResource: 'energy',
    inputPerOutput: 0.4,
    credit: 7200,
    material: 120,
    capacity: 2.3,
    baseDegradationRate: 1.0,
    description: 'High-density helical tube bio-reactor cultivating spirulina and lipid-rich biomass cultures with rapid doubling times.',
  },
  'cellular-meat-bioreactor': {
    name: 'Cultured Protein Synthesizer',
    category: 'food',
    tier: 3,
    output: 'food',
    inputResource: 'energy',
    inputPerOutput: 0.5,
    credit: 15000,
    material: 240,
    capacity: 3.6,
    baseDegradationRate: 1.1,
    description: 'Sterile perfusion bioreactor cultivating pure cellular muscle and connective protein tissues without livestock overhead.',
  },
  'biosphere-dome': {
    name: 'Automated Climate Biome',
    category: 'food',
    tier: 4,
    output: 'food',
    inputResource: 'energy',
    inputPerOutput: 0.6,
    credit: 34000,
    material: 480,
    capacity: 5.0,
    baseDegradationRate: 1.3,
    description: 'Pressurized geodesic planetary enclosure supporting polyculture self-regulating agricultural ecosystems.',
    requiredTech: 'Food Synthesis',
  },

  // --- RAW MINERAL & SUBTERRANEAN MINING ---
  'sub-crustal-bore-drill': {
    name: 'Deep Rotary Bore Drill',
    category: 'extraction',
    tier: 1,
    output: 'material',
    inputResource: 'energy',
    inputPerOutput: 0.4,
    credit: 3600,
    material: 60,
    capacity: 1.5,
    baseDegradationRate: 1.1,
    description: 'Diamond-tipped rotary drill shaft penetrating upper crustal strata for basic mineral ore extraction.',
  },
  'automated-strip-excavator': {
    name: 'Continuous Bucket-Wheel Excavator',
    category: 'extraction',
    tier: 2,
    output: 'material',
    inputResource: 'energy',
    inputPerOutput: 0.5,
    credit: 7800,
    material: 135,
    capacity: 2.4,
    baseDegradationRate: 1.2,
    description: 'Giant multi-bucket continuous surface mining crawler excavating heavy tonnage of silicate and metallic ores.',
  },
  'plasma-quarry-harvester': {
    name: 'Plasma Arc Mineral Slicer',
    category: 'extraction',
    tier: 3,
    output: 'material',
    inputResource: 'energy',
    inputPerOutput: 0.7,
    credit: 16500,
    material: 260,
    capacity: 3.8,
    baseDegradationRate: 1.3,
    description: 'High-temperature ionized plasma torch grid extracting hyper-concentrated rare-earth minerals.',
  },
  'asteroid-impact-smelter': {
    name: 'Orbital Asteroid Snare & Smelter',
    category: 'extraction',
    tier: 4,
    output: 'material',
    inputResource: 'energy',
    inputPerOutput: 0.8,
    credit: 36000,
    material: 520,
    capacity: 5.2,
    baseDegradationRate: 1.5,
    description: 'Near-space tug and mass-driver platform capturing mineral-rich platinum-group metallic planetesimals.',
    requiredTech: 'Deep Crust Bore Extraction',
  },

  // --- COMPONENT FABRICATION & METALLURGY ---
  'cnc-machining-cell': {
    name: '5-Axis Precision CNC Mill',
    category: 'components',
    tier: 1,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.2,
    credit: 4000,
    material: 70,
    capacity: 1.4,
    baseDegradationRate: 1.0,
    description: 'High-speed automated milling and lathe center producing standardized mechanical linkages and gears.',
  },
  'robotic-assembly-line': {
    name: 'Multi-Arm Autonomous Assembly Line',
    category: 'components',
    tier: 2,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.1,
    credit: 8400,
    material: 145,
    capacity: 2.2,
    baseDegradationRate: 1.1,
    description: 'Coordinated 6-DOF robotic manipulator conveyor building complex mechanical, electrical, and pneumatic subassemblies.',
  },
  'nano-alloy-foundry': {
    name: 'Molecular Sintering & Alloy Forge',
    category: 'components',
    tier: 3,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.0,
    credit: 17500,
    material: 280,
    capacity: 3.6,
    baseDegradationRate: 1.2,
    description: 'Laser powder-bed fusion and atomic lattice foundry forging ultra-durable carbon-titanium composite components.',
  },
  'quantum-fabrication-rig': {
    name: 'Sub-Atomic Lattice Fabricator',
    category: 'components',
    tier: 4,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 0.9,
    credit: 38000,
    material: 540,
    capacity: 5.0,
    baseDegradationRate: 1.4,
    description: 'Topologically protected quantum nanotech assembler synthesizing defect-free high-spec machinery components.',
    requiredTech: 'Automated Assembly',
  },

  // --- COMPUTE & QUANTUM DATA NODES ---
  'server-cluster-rack': {
    name: 'Edge Data Server Cluster',
    category: 'compute',
    tier: 1,
    output: 'compute',
    inputResource: 'energy',
    inputPerOutput: 0.5,
    credit: 4200,
    material: 75,
    capacity: 1.3,
    baseDegradationRate: 0.9,
    description: 'Liquid-cooled high-density blade servers providing distributed computational cycles for telemetry and research.',
  },
  'quantum-annealing-rig': {
    name: 'Cryogenic Quantum Core',
    category: 'compute',
    tier: 2,
    output: 'compute',
    inputResource: 'energy',
    inputPerOutput: 0.7,
    credit: 9200,
    material: 160,
    capacity: 2.1,
    baseDegradationRate: 1.0,
    description: 'Superconducting qubit processor operating at milli-Kelvin temperatures to solve complex algorithmic optimizations.',
  },
  'neural-synapse-mainframe': {
    name: 'Neuromorphic AI Matrix',
    category: 'compute',
    tier: 3,
    output: 'compute',
    inputResource: 'energy',
    inputPerOutput: 0.8,
    credit: 19000,
    material: 310,
    capacity: 3.5,
    baseDegradationRate: 1.2,
    description: 'Massive memristor-based bio-mimetic neural network processing vast real-time simulations and strategic analytics.',
  },
  'orbital-satellite-relay': {
    name: 'Orbital Sensor Constellation',
    category: 'compute',
    tier: 4,
    output: 'compute',
    inputResource: 'energy',
    inputPerOutput: 1.0,
    credit: 40000,
    material: 580,
    capacity: 4.8,
    baseDegradationRate: 1.3,
    description: 'Planetary mesh satellite constellation providing uninterrupted deep telemetry, planetary imaging, and quantum communications.',
    requiredTech: 'Cryogenic Supercomputing',
  },

  // --- SPECIALIZED ROBOTICS, HABITATS & HEAVY INDUSTRY ---
  'service-robot-hub': {
    name: 'Autonomous Service Drone Hub',
    category: 'specialized',
    tier: 2,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 0.9,
    credit: 7500,
    material: 125,
    capacity: 1.8,
    baseDegradationRate: 0.8,
    description: 'Rapid-dispatch robotic service bay specializing in machine conditioning, preventative maintenance, and repair parts.',
  },
  'modular-housing-printer': {
    name: '3D Habitat Constructor',
    category: 'specialized',
    tier: 2,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.4,
    credit: 8800,
    material: 150,
    capacity: 2.0,
    baseDegradationRate: 1.1,
    description: 'Large-scale gantry 3D printer extruding geopolymer structures, residential modules, and urban habitat infrastructure.',
  },
  'bio-synthetic-refinery': {
    name: 'Enzymatic Biochemical Refinery',
    category: 'specialized',
    tier: 3,
    output: 'components',
    inputResource: 'food',
    inputPerOutput: 1.0,
    credit: 16000,
    material: 250,
    capacity: 3.2,
    baseDegradationRate: 1.1,
    description: 'Continuous catalytic bio-reactor converting raw organic carbohydrates into bio-plastics, lubricants, and polymers.',
  },
  'orbital-shipyard-cradle': {
    name: 'Microgravity Heavy Drydock',
    category: 'specialized',
    tier: 4,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.2,
    credit: 45000,
    material: 650,
    capacity: 5.5,
    baseDegradationRate: 1.4,
    description: 'Zero-gravity orbital construction scaffolding capable of assembling super-heavy industrial machinery and space transports.',
    requiredTech: 'Orbital Logistics',
  },

  // --- BACKWARD COMPATIBILITY ALIASES ---
  extractor: {
    name: 'Sub-Crustal Extractor',
    category: 'extraction',
    tier: 1,
    output: 'material',
    inputResource: 'energy',
    inputPerOutput: 0.4,
    credit: 4200,
    material: 80,
    capacity: 2.0,
    baseDegradationRate: 1.0,
    description: 'Diamond-tipped rotary bore drill penetrating upper crustal strata for mineral ore extraction.',
  },
  'energy-array': {
    name: 'Solar Energy Array',
    category: 'energy',
    tier: 1,
    output: 'energy',
    inputResource: 'material',
    inputPerOutput: 0.05,
    credit: 3600,
    material: 60,
    capacity: 2.0,
    baseDegradationRate: 0.8,
    description: 'High-efficiency ground photovoltaic array generating continuous electrical energy.',
  },
  'food-synthesizer': {
    name: 'Bio-Food Synthesizer',
    category: 'food',
    tier: 1,
    output: 'food',
    inputResource: 'energy',
    inputPerOutput: 0.3,
    credit: 4400,
    material: 75,
    capacity: 1.8,
    baseDegradationRate: 0.9,
    description: 'Automated bio-nutrient cultivation chamber for metabolic food production.',
  },
  'compute-node': {
    name: 'Quantum Compute Node',
    category: 'compute',
    tier: 1,
    output: 'compute',
    inputResource: 'energy',
    inputPerOutput: 0.5,
    credit: 5200,
    material: 100,
    capacity: 1.5,
    baseDegradationRate: 0.9,
    description: 'High-density computational cluster executing simulation algorithms and research processing.',
  },
  fabricator: {
    name: 'Component Fabricator',
    category: 'components',
    tier: 1,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.2,
    credit: 4800,
    material: 90,
    capacity: 1.8,
    baseDegradationRate: 1.0,
    description: 'Precision manufacturing cell assembling mechanical parts and structural modules.',
  },
  'housing-fabricator': {
    name: 'Housing Fabricator',
    category: 'specialized',
    tier: 2,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.4,
    credit: 5000,
    material: 110,
    capacity: 1.6,
    baseDegradationRate: 1.0,
    description: 'Structural printer fabricating modular habitat units and residential blocks.',
  },
  'research-cluster': {
    name: 'R&D Research Cluster',
    category: 'compute',
    tier: 2,
    output: 'compute',
    inputResource: 'energy',
    inputPerOutput: 0.7,
    credit: 7000,
    material: 140,
    capacity: 2.2,
    baseDegradationRate: 1.0,
    description: 'Dedicated scientific compute matrix accelerating technology research and patent discoveries.',
  },
  'service-robot': {
    name: 'Service Robot Unit',
    category: 'specialized',
    tier: 2,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 0.9,
    credit: 4500,
    material: 45,
    capacity: 1.5,
    baseDegradationRate: 0.8,
    description: 'Autonomous maintenance drone preserving machine condition.',
  },
  'assembly-line': {
    name: 'Industrial Assembly Line',
    category: 'components',
    tier: 2,
    output: 'components',
    inputResource: 'material',
    inputPerOutput: 1.1,
    credit: 8000,
    material: 130,
    capacity: 2.2,
    baseDegradationRate: 1.1,
    description: 'Robotic assembly conveyor for high-volume component production.',
  },
};

export function productionCatalogResponse(): Response {
  return Response.json({
    sectors: [
      {
        id: 'energy',
        name: 'Energy & Power Grids',
        output: 'energy',
        machineTypes: [
          'solar-photovoltaic-array',
          'geothermal-tap',
          'fusion-tokamak-rig',
          'orbital-solar-collector',
          'energy-array',
        ],
        catalog: [
          { type: 'solar-photovoltaic-array', ...MACHINE_CATALOG['solar-photovoltaic-array'] },
          { type: 'geothermal-tap', ...MACHINE_CATALOG['geothermal-tap'] },
          { type: 'fusion-tokamak-rig', ...MACHINE_CATALOG['fusion-tokamak-rig'] },
          { type: 'orbital-solar-collector', ...MACHINE_CATALOG['orbital-solar-collector'] },
        ],
      },
      {
        id: 'food',
        name: 'Food & Bio-Cultivation',
        output: 'food',
        machineTypes: [
          'hydroponic-tower',
          'algae-photobioreactor',
          'cellular-meat-bioreactor',
          'biosphere-dome',
          'food-synthesizer',
        ],
        catalog: [
          { type: 'hydroponic-tower', ...MACHINE_CATALOG['hydroponic-tower'] },
          { type: 'algae-photobioreactor', ...MACHINE_CATALOG['algae-photobioreactor'] },
          { type: 'cellular-meat-bioreactor', ...MACHINE_CATALOG['cellular-meat-bioreactor'] },
          { type: 'biosphere-dome', ...MACHINE_CATALOG['biosphere-dome'] },
        ],
      },
      {
        id: 'extraction',
        name: 'Mineral Mining & Excavation',
        output: 'material',
        machineTypes: [
          'sub-crustal-bore-drill',
          'automated-strip-excavator',
          'plasma-quarry-harvester',
          'asteroid-impact-smelter',
          'extractor',
        ],
        catalog: [
          { type: 'sub-crustal-bore-drill', ...MACHINE_CATALOG['sub-crustal-bore-drill'] },
          { type: 'automated-strip-excavator', ...MACHINE_CATALOG['automated-strip-excavator'] },
          { type: 'plasma-quarry-harvester', ...MACHINE_CATALOG['plasma-quarry-harvester'] },
          { type: 'asteroid-impact-smelter', ...MACHINE_CATALOG['asteroid-impact-smelter'] },
        ],
      },
      {
        id: 'components',
        name: 'Components, Alloys & Robotics',
        output: 'components',
        machineTypes: [
          'cnc-machining-cell',
          'robotic-assembly-line',
          'nano-alloy-foundry',
          'quantum-fabrication-rig',
          'fabricator',
          'assembly-line',
        ],
        catalog: [
          { type: 'cnc-machining-cell', ...MACHINE_CATALOG['cnc-machining-cell'] },
          { type: 'robotic-assembly-line', ...MACHINE_CATALOG['robotic-assembly-line'] },
          { type: 'nano-alloy-foundry', ...MACHINE_CATALOG['nano-alloy-foundry'] },
          { type: 'quantum-fabrication-rig', ...MACHINE_CATALOG['quantum-fabrication-rig'] },
        ],
      },
      {
        id: 'compute',
        name: 'Compute, Intelligence & R&D',
        output: 'compute',
        machineTypes: [
          'server-cluster-rack',
          'quantum-annealing-rig',
          'neural-synapse-mainframe',
          'orbital-satellite-relay',
          'compute-node',
          'research-cluster',
        ],
        catalog: [
          { type: 'server-cluster-rack', ...MACHINE_CATALOG['server-cluster-rack'] },
          { type: 'quantum-annealing-rig', ...MACHINE_CATALOG['quantum-annealing-rig'] },
          { type: 'neural-synapse-mainframe', ...MACHINE_CATALOG['neural-synapse-mainframe'] },
          { type: 'orbital-satellite-relay', ...MACHINE_CATALOG['orbital-satellite-relay'] },
        ],
      },
      {
        id: 'specialized',
        name: 'Specialized Robotics & Habitats',
        output: 'components',
        machineTypes: [
          'service-robot-hub',
          'modular-housing-printer',
          'bio-synthetic-refinery',
          'orbital-shipyard-cradle',
          'service-robot',
          'housing-fabricator',
        ],
        catalog: [
          { type: 'service-robot-hub', ...MACHINE_CATALOG['service-robot-hub'] },
          { type: 'modular-housing-printer', ...MACHINE_CATALOG['modular-housing-printer'] },
          { type: 'bio-synthetic-refinery', ...MACHINE_CATALOG['bio-synthetic-refinery'] },
          { type: 'orbital-shipyard-cradle', ...MACHINE_CATALOG['orbital-shipyard-cradle'] },
        ],
      },
      { id: 'it-services', name: 'IT Services', output: 'service', machineTypes: [] },
      { id: 'consulting', name: 'Consulting', output: 'service', machineTypes: [] },
      { id: 'logistics', name: 'Logistics', output: 'service', machineTypes: [] },
      { id: 'healthcare', name: 'Healthcare', output: 'service', machineTypes: [] },
      { id: 'education', name: 'Education', output: 'service', machineTypes: [] },
    ],
    catalog: MACHINE_CATALOG,
    rules: { serverAuthoritative: true, productionRequiresUtilization: true, depreciationApplied: true },
    persistence: 'planetscale-postgres',
  });
}
