export type BuildingCategory =
  | 'commercial'
  | 'energy'
  | 'food'
  | 'manufacturing'
  | 'compute'
  | 'civic';

export type OwnershipClass = 'private' | 'civic' | 'public_investment';
export type OperatingPolicy = 'balanced' | 'high_output' | 'eco_reserve' | 'overclock';

export interface BuildingCatalogItem {
  type: string;
  name: string;
  category: BuildingCategory;
  slotFootprint: number; // 1 to 8 city slots
  defaultOwnershipClass: OwnershipClass;
  tier: number; // 1 to 4
  baseCreditCost: number;
  baseMaterialCost: number;
  dailyEnergyUpkeep: number;
  dailyFoodUpkeep: number;
  dailyMaterialsUpkeep: number;
  dailyComponentsUpkeep: number;
  dailyComputeUpkeep: number;
  dailyStaffingCredits: number;
  dailyCreditRevenue: number;
  resourceOutputType: 'credits' | 'energy' | 'food' | 'material' | 'components' | 'compute';
  resourceOutputAmount: number;
  description: string;
  civicBenefit?: string;
  requiredTech?: string;
}

/**
 * Authoritative Earth Urban Real Estate & Building Blueprint Catalog.
 * All buildings are fully self-contained economic units that consume
 * physical footprints (city slots), operating resources, and maintenance buffers,
 * producing credits, commodities, or municipal citizen dividends.
 */
export const BUILDING_CATALOG: Record<string, BuildingCatalogItem> = {
  // ==================== COMMERCIAL SECTOR ====================
  'restaurant': {
    type: 'restaurant',
    name: 'Bistro & Molecular Diner',
    category: 'commercial',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 8500,
    baseMaterialCost: 120,
    dailyEnergyUpkeep: 0.50,
    dailyFoodUpkeep: 0.30,
    dailyMaterialsUpkeep: 0.05,
    dailyComponentsUpkeep: 0.05,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 120,
    dailyCreditRevenue: 620,
    resourceOutputType: 'credits',
    resourceOutputAmount: 620,
    description: 'Boutique dining establishment synthesizing culinary dishes into direct credit revenue from city residents.',
  },
  'retail-store': {
    type: 'retail-store',
    name: 'Retail Boutique & Tools Outlet',
    category: 'commercial',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 9200,
    baseMaterialCost: 140,
    dailyEnergyUpkeep: 0.40,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.10,
    dailyComponentsUpkeep: 0.15,
    dailyComputeUpkeep: 0.05,
    dailyStaffingCredits: 140,
    dailyCreditRevenue: 710,
    resourceOutputType: 'credits',
    resourceOutputAmount: 710,
    description: 'Consumer storefront supplying standardized tools, consumer gear, and manufactured hardware to urban dwellers.',
  },
  'holo-entertainment': {
    type: 'holo-entertainment',
    name: 'Holo-Entertainment Arena',
    category: 'commercial',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 24000,
    baseMaterialCost: 350,
    dailyEnergyUpkeep: 1.80,
    dailyFoodUpkeep: 0.20,
    dailyMaterialsUpkeep: 0,
    dailyComponentsUpkeep: 0.25,
    dailyComputeUpkeep: 0.80,
    dailyStaffingCredits: 350,
    dailyCreditRevenue: 2150,
    resourceOutputType: 'credits',
    resourceOutputAmount: 2150,
    description: 'Immersive holographic arena hosting high-ticket athletic tournaments, virtual arts, and cultural simulations.',
  },
  'commercial-mall': {
    type: 'commercial-mall',
    name: 'Metropolitan Commercial Mega-Mall',
    category: 'commercial',
    slotFootprint: 4,
    defaultOwnershipClass: 'public_investment',
    tier: 3,
    baseCreditCost: 65000,
    baseMaterialCost: 950,
    dailyEnergyUpkeep: 3.50,
    dailyFoodUpkeep: 1.20,
    dailyMaterialsUpkeep: 0.20,
    dailyComponentsUpkeep: 0.80,
    dailyComputeUpkeep: 0.50,
    dailyStaffingCredits: 850,
    dailyCreditRevenue: 4800,
    resourceOutputType: 'credits',
    resourceOutputAmount: 4800,
    description: 'Massive multi-story shopping, dining, and commercial hub generating large commercial returns and municipal taxes.',
    requiredTech: 'Automated Assembly',
  },

  // ==================== ENERGY UTILITY SECTOR ====================
  'solar-field': {
    type: 'solar-field',
    name: 'Photovoltaic Solar Field',
    category: 'energy',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 7800,
    baseMaterialCost: 110,
    dailyEnergyUpkeep: 0,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.10,
    dailyComponentsUpkeep: 0.05,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 80,
    dailyCreditRevenue: 320,
    resourceOutputType: 'energy',
    resourceOutputAmount: 8.5,
    description: 'Ground-level solar collector array converting solar radiation into clean megawatt grid power.',
  },
  'geothermal-tap': {
    type: 'geothermal-tap',
    name: 'Pressurized Geothermal Well',
    category: 'energy',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 22000,
    baseMaterialCost: 320,
    dailyEnergyUpkeep: 0,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.25,
    dailyComponentsUpkeep: 0.20,
    dailyComputeUpkeep: 0.10,
    dailyStaffingCredits: 220,
    dailyCreditRevenue: 650,
    resourceOutputType: 'energy',
    resourceOutputAmount: 22.0,
    description: 'Deep mantle bore harnessing high-pressure volcanic heat for uninterrupted baseline power generation.',
  },
  'fusion-reactor': {
    type: 'fusion-reactor',
    name: 'Magnetic Fusion Dynamo',
    category: 'energy',
    slotFootprint: 4,
    defaultOwnershipClass: 'public_investment',
    tier: 3,
    baseCreditCost: 75000,
    baseMaterialCost: 1150,
    dailyEnergyUpkeep: 0,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.50,
    dailyComponentsUpkeep: 0.80,
    dailyComputeUpkeep: 0.60,
    dailyStaffingCredits: 900,
    dailyCreditRevenue: 2400,
    resourceOutputType: 'energy',
    resourceOutputAmount: 65.0,
    description: 'Deuterium-tritium magnetic confinement tokamak generating extreme-density power for municipal districts.',
    requiredTech: 'Cryogenic Supercomputing',
  },

  // ==================== FOOD & AGRICULTURE SECTOR ====================
  'hydroponic-pod': {
    type: 'hydroponic-pod',
    name: 'Vertical Aeroponic Tower',
    category: 'food',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 8200,
    baseMaterialCost: 115,
    dailyEnergyUpkeep: 0.80,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.10,
    dailyComponentsUpkeep: 0.05,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 110,
    dailyCreditRevenue: 340,
    resourceOutputType: 'food',
    resourceOutputAmount: 7.5,
    description: 'Multi-layer aeroponic cultivation tower growing nutrient-dense crops under automated LED spectrums.',
  },
  'algae-bioreactor': {
    type: 'algae-bioreactor',
    name: 'Micro-Algae Bio-Vat',
    category: 'food',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 16500,
    baseMaterialCost: 240,
    dailyEnergyUpkeep: 1.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.15,
    dailyComponentsUpkeep: 0.10,
    dailyComputeUpkeep: 0.10,
    dailyStaffingCredits: 180,
    dailyCreditRevenue: 520,
    resourceOutputType: 'food',
    resourceOutputAmount: 16.0,
    description: 'Continuous bio-culture vats refining rapid-growth spirulina and biomass reserves.',
  },
  'protein-refinery': {
    type: 'protein-refinery',
    name: 'Cellular Meat & Protein Refinery',
    category: 'food',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 26000,
    baseMaterialCost: 380,
    dailyEnergyUpkeep: 2.00,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.20,
    dailyComponentsUpkeep: 0.25,
    dailyComputeUpkeep: 0.20,
    dailyStaffingCredits: 320,
    dailyCreditRevenue: 980,
    resourceOutputType: 'food',
    resourceOutputAmount: 28.0,
    description: 'Sterile tissue-culture facility producing clean molecular meats and organic polymers.',
  },
  'biosphere-dome': {
    type: 'biosphere-dome',
    name: 'Atmospheric Biosphere Agri-Dome',
    category: 'food',
    slotFootprint: 3,
    defaultOwnershipClass: 'public_investment',
    tier: 3,
    baseCreditCost: 62000,
    baseMaterialCost: 920,
    dailyEnergyUpkeep: 3.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.30,
    dailyComponentsUpkeep: 0.60,
    dailyComputeUpkeep: 0.40,
    dailyStaffingCredits: 750,
    dailyCreditRevenue: 2800,
    resourceOutputType: 'food',
    resourceOutputAmount: 55.0,
    description: 'Pressurized geo-engineered agricultural dome sustaining full-spectrum orchards and agricultural yields.',
    requiredTech: 'Automated Assembly',
  },

  // ==================== INDUSTRIAL & MANUFACTURING SECTOR ====================
  'machining-cell': {
    type: 'machining-cell',
    name: 'Precision CNC Machining Cell',
    category: 'manufacturing',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 9500,
    baseMaterialCost: 150,
    dailyEnergyUpkeep: 1.00,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 1.20,
    dailyComponentsUpkeep: 0,
    dailyComputeUpkeep: 0.05,
    dailyStaffingCredits: 130,
    dailyCreditRevenue: 420,
    resourceOutputType: 'components',
    resourceOutputAmount: 6.0,
    description: 'Compact 5-axis robotic milling cell fabricating standardized components from raw materials.',
  },
  'fabrication-plant': {
    type: 'fabrication-plant',
    name: 'Automated Fabrication Plant',
    category: 'manufacturing',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 28000,
    baseMaterialCost: 420,
    dailyEnergyUpkeep: 2.40,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 2.80,
    dailyComponentsUpkeep: 0.10,
    dailyComputeUpkeep: 0.15,
    dailyStaffingCredits: 380,
    dailyCreditRevenue: 1250,
    resourceOutputType: 'components',
    resourceOutputAmount: 18.0,
    description: 'Heavy industrial plant featuring synchronized multi-arm robotic assembly lines and laser welders.',
  },
  'chemical-foundry': {
    type: 'chemical-foundry',
    name: 'Deep Chemical & Alloy Foundry',
    category: 'manufacturing',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 25000,
    baseMaterialCost: 390,
    dailyEnergyUpkeep: 2.60,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0,
    dailyComponentsUpkeep: 0.20,
    dailyComputeUpkeep: 0.10,
    dailyStaffingCredits: 340,
    dailyCreditRevenue: 950,
    resourceOutputType: 'material',
    resourceOutputAmount: 22.0,
    description: 'High-temperature metallurgical furnace extracting and refining structural metal ingots and composites.',
  },
  'quantum-fab': {
    type: 'quantum-fab',
    name: 'Quantum Microelectronics Fab',
    category: 'manufacturing',
    slotFootprint: 3,
    defaultOwnershipClass: 'public_investment',
    tier: 3,
    baseCreditCost: 68000,
    baseMaterialCost: 980,
    dailyEnergyUpkeep: 4.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 1.50,
    dailyComponentsUpkeep: 0.60,
    dailyComputeUpkeep: 1.50,
    dailyStaffingCredits: 820,
    dailyCreditRevenue: 3400,
    resourceOutputType: 'components',
    resourceOutputAmount: 42.0,
    description: 'Sub-nanometer lithography cleanroom producing advanced quantum cores, logic gates, and sensor packages.',
    requiredTech: 'Cryogenic Supercomputing',
  },

  // ==================== COMPUTE & R&D SECTOR ====================
  'data-relay': {
    type: 'data-relay',
    name: 'Sub-Network Data Relay',
    category: 'compute',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 9800,
    baseMaterialCost: 130,
    dailyEnergyUpkeep: 1.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0,
    dailyComponentsUpkeep: 0.10,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 100,
    dailyCreditRevenue: 380,
    resourceOutputType: 'compute',
    resourceOutputAmount: 8.0,
    description: 'High-bandwidth optical telemetry routing hub providing low-latency computational capacity.',
  },
  'server-farm': {
    type: 'server-farm',
    name: 'Neural Data Center & Server Farm',
    category: 'compute',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 27000,
    baseMaterialCost: 390,
    dailyEnergyUpkeep: 3.00,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0,
    dailyComponentsUpkeep: 0.30,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 350,
    dailyCreditRevenue: 1100,
    resourceOutputType: 'compute',
    resourceOutputAmount: 25.0,
    description: 'Sub-surface immersion-cooled server racks processing planetary AI and enterprise data workloads.',
  },
  'corporate-lab': {
    type: 'corporate-lab',
    name: 'Corporate R&D Laboratory',
    category: 'compute',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 2,
    baseCreditCost: 29000,
    baseMaterialCost: 410,
    dailyEnergyUpkeep: 2.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.10,
    dailyComponentsUpkeep: 0.35,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 420,
    dailyCreditRevenue: 1450,
    resourceOutputType: 'compute',
    resourceOutputAmount: 20.0,
    description: 'Advanced laboratory facility dedicated to researching corporate patent commons and technological breakthroughs.',
  },
  'orbital-observatory': {
    type: 'orbital-observatory',
    name: 'Orbital Uplink Observatory',
    category: 'compute',
    slotFootprint: 3,
    defaultOwnershipClass: 'public_investment',
    tier: 3,
    baseCreditCost: 64000,
    baseMaterialCost: 920,
    dailyEnergyUpkeep: 3.80,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.20,
    dailyComponentsUpkeep: 0.70,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 780,
    dailyCreditRevenue: 3100,
    resourceOutputType: 'compute',
    resourceOutputAmount: 58.0,
    description: 'Deep-space communication array linking planetary operations with orbital constellations and lunar relays.',
    requiredTech: 'Orbital Logistics',
  },

  // ==================== CIVIC & PUBLIC INFRASTRUCTURE ====================
  'geothermal-grid': {
    type: 'geothermal-grid',
    name: 'Central Geothermal Power Grid',
    category: 'civic',
    slotFootprint: 6,
    defaultOwnershipClass: 'civic',
    tier: 3,
    baseCreditCost: 85000,
    baseMaterialCost: 1400,
    dailyEnergyUpkeep: 0,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.80,
    dailyComponentsUpkeep: 0.60,
    dailyComputeUpkeep: 0.20,
    dailyStaffingCredits: 1100,
    dailyCreditRevenue: 2800,
    resourceOutputType: 'energy',
    resourceOutputAmount: 85.0,
    description: 'Massive civic deep-bore thermal tapping facility supplying base-load energy to the entire municipality.',
    civicBenefit: 'Boosts City Energy Capacity (+80) and funds the 70/30 Citizen Dividend pool.',
  },
  'transit-terminus': {
    type: 'transit-terminus',
    name: 'Central Transit & Maglev Hub',
    category: 'civic',
    slotFootprint: 4,
    defaultOwnershipClass: 'civic',
    tier: 2,
    baseCreditCost: 65000,
    baseMaterialCost: 1050,
    dailyEnergyUpkeep: 2.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.40,
    dailyComponentsUpkeep: 0.80,
    dailyComputeUpkeep: 0.50,
    dailyStaffingCredits: 950,
    dailyCreditRevenue: 3200,
    resourceOutputType: 'credits',
    resourceOutputAmount: 3200,
    description: 'Automated Maglev and drone logistics terminal facilitating rapid freight and passenger transit across the city.',
    civicBenefit: 'Boosts City Connectivity (+60) and provides recurring transit fare dividends to citizens.',
  },
  'general-hospital': {
    type: 'general-hospital',
    name: 'Metropolitan General Hospital',
    category: 'civic',
    slotFootprint: 3,
    defaultOwnershipClass: 'civic',
    tier: 2,
    baseCreditCost: 72000,
    baseMaterialCost: 1150,
    dailyEnergyUpkeep: 2.80,
    dailyFoodUpkeep: 1.20,
    dailyMaterialsUpkeep: 0.20,
    dailyComponentsUpkeep: 0.90,
    dailyComputeUpkeep: 0.80,
    dailyStaffingCredits: 1050,
    dailyCreditRevenue: 2200,
    resourceOutputType: 'credits',
    resourceOutputAmount: 2200,
    description: 'State-of-the-art public healthcare complex providing automated triage and medical cybernetics.',
    civicBenefit: 'Boosts City Health Capacity (+50) and halts natural health degradation for resident citizens.',
  },
  'orbital-spaceport': {
    type: 'orbital-spaceport',
    name: 'Planetary Spaceport & Mass Driver',
    category: 'civic',
    slotFootprint: 8,
    defaultOwnershipClass: 'public_investment',
    tier: 4,
    baseCreditCost: 180000,
    baseMaterialCost: 2800,
    dailyEnergyUpkeep: 6.50,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 1.20,
    dailyComponentsUpkeep: 2.50,
    dailyComputeUpkeep: 2.00,
    dailyStaffingCredits: 2400,
    dailyCreditRevenue: 9500,
    resourceOutputType: 'credits',
    resourceOutputAmount: 9500,
    description: 'Sovereign aerospace hub capable of handling sub-orbital shuttles, orbital freighters, and interplanetary transports.',
    civicBenefit: 'Unlocks high-volume orbital trade contracts and massive dividend distributions to shareholders and citizens.',
    requiredTech: 'Orbital Logistics',
  },
};
