export type BuildingCategory =
  | 'commercial'
  | 'manufacturing'
  | 'energy'
  | 'medical'
  | 'compute'
  | 'civic'
  | 'orbital'
  | 'food';

export type OwnershipClass = 'private' | 'civic' | 'public_investment';
export type OperatingPolicy = 'balanced' | 'high_output' | 'eco_reserve' | 'overclock';

export interface RequiredPatentSpec {
  patentId: string;
  patentName: string;
  owningCorporationId: string;
  owningCorporationName: string;
  privateLicenseCostCrd: number;
  privateDailyRoyaltyCrd: number;
  cityCivicLicenseCostCrd: number;
  termDays: number;
  description: string;
}

export interface BuildingTierSpec {
  tier: number;
  name: string;
  upgradeCreditCost: number;
  upgradeMaterialCost: number;
  upgradeComponentsCost?: number;
  upgradeComputeCost?: number;
  dailyCreditRevenue: number;
  dailyOperatingCredits: number;
  dailyEnergyUpkeep: number;
  dailyFoodUpkeep?: number;
  dailyMaterialsUpkeep?: number;
  dailyComponentsUpkeep?: number;
  dailyComputeUpkeep?: number;
  resourceOutputType?: 'credits' | 'energy' | 'food' | 'material' | 'components' | 'compute';
  resourceOutputAmount?: number;
  unlockedPerks: string[];
  requiredCityPopulation?: number;
  requiredPatent?: RequiredPatentSpec;
  description: string;
}

export interface BuildingCatalogItem {
  type: string;
  name: string;
  category: BuildingCategory;
  slotFootprint: number; // 1 to 8 city slots
  defaultOwnershipClass: OwnershipClass;
  tier: number; // base starting tier
  baseCreditCost: number;
  baseMaterialCost: number;
  dailyEnergyUpkeep: number;
  dailyFoodUpkeep: number;
  dailyMaterialsUpkeep: number;
  dailyComponentsUpkeep: number;
  dailyComputeUpkeep: number;
  dailyStaffingCredits: number;
  dailyCreditRevenue: number;
  resourceOutputType: 'credits' | 'energy' | 'food' | 'material' | 'components' | 'compute';
  resourceOutputAmount: number;
  estimatedPaybackDays: number;
  resourceSensitivity: 'low' | 'medium' | 'high';
  maintenanceRisk: 'low' | 'medium' | 'high';
  primaryEconomicPurpose: string;
  description: string;
  civicBenefit?: string;
  requiredPatent?: RequiredPatentSpec;
  minCityPopulation?: number;
  tiers: BuildingTierSpec[];
}

/**
 * Authoritative Earth Urban Real Estate & Building Blueprint Catalog.
 * All buildings are fully self-contained economic units that consume
 * physical footprints (city slots), operating resources, and maintenance buffers,
 * producing credits, commodities, or municipal citizen dividends.
 *
 * Foundational EARTH technologies remain permanently open to all players.
 * Advanced facilities and high-tier branches are regulated by Corporate Patents,
 * supporting 3 licensing levels:
 * 1. Corporate Member (Free with membership)
 * 2. Private Building License (30-day term + royalties)
 * 3. City-Wide Civic License (Municipal infrastructure access)
 */
export const BUILDING_CATALOG: Record<string, BuildingCatalogItem> = {
  // ==================== 1. COMMERCIAL SECTOR (High Credit Yields) ====================
  'restaurant': {
    type: 'restaurant',
    name: 'Bistro & Molecular Restaurant',
    category: 'commercial',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 8500,
    baseMaterialCost: 120,
    dailyEnergyUpkeep: 0.50,
    dailyFoodUpkeep: 0.30,
    dailyMaterialsUpkeep: 0.05,
    dailyComponentsUpkeep: 0.05,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 120,
    dailyCreditRevenue: 620,
    resourceOutputType: 'credits',
    resourceOutputAmount: 620,
    estimatedPaybackDays: 17,
    resourceSensitivity: 'medium',
    maintenanceRisk: 'low',
    primaryEconomicPurpose: 'Liquid Credit Profit & Resident Consumption',
    description: 'Boutique dining establishment synthesizing culinary dishes into direct credit revenue from city residents.',
    tiers: [
      {
        tier: 1,
        name: 'Bistro & Molecular Diner',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 620,
        dailyOperatingCredits: 120,
        dailyEnergyUpkeep: 0.50,
        dailyFoodUpkeep: 0.30,
        unlockedPerks: ['Basic Molecular Dining', 'Resident Table Turnover'],
        description: 'Base foundational dining eatery (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Gourmet Gastronomy Lounge',
        upgradeCreditCost: 7500,
        upgradeMaterialCost: 90,
        upgradeComponentsCost: 10,
        dailyCreditRevenue: 1450,
        dailyOperatingCredits: 220,
        dailyEnergyUpkeep: 0.90,
        dailyFoodUpkeep: 0.55,
        unlockedPerks: ['Premium Tasting Menu', 'Corporate Catering Contract'],
        requiredCityPopulation: 10,
        description: 'Upscale gastronomy lounge attracting executive patronage.',
      },
      {
        tier: 3,
        name: 'Planetary Grand Bistro',
        upgradeCreditCost: 18000,
        upgradeMaterialCost: 210,
        upgradeComponentsCost: 35,
        upgradeComputeCost: 25,
        dailyCreditRevenue: 3400,
        dailyOperatingCredits: 480,
        dailyEnergyUpkeep: 1.60,
        dailyFoodUpkeep: 1.10,
        unlockedPerks: ['District Franchise Rights', 'Tourism Influx Multiplier (+15%)'],
        requiredCityPopulation: 25,
        requiredPatent: {
          patentId: 'PAT-HOSP-01',
          patentName: 'Automated Service & Molecular Gastronomy Protocol',
          owningCorporationId: 'CORP-GENESIS',
          owningCorporationName: 'Genesis Horizon Bio-Systems',
          privateLicenseCostCrd: 4500,
          privateDailyRoyaltyCrd: 60,
          cityCivicLicenseCostCrd: 16000,
          termDays: 30,
          description: 'Proprietary robotic server arrays and molecular flavor synthesis algorithms.',
        },
        description: 'Iconic planetary dining destination driving urban tourism.',
      },
    ],
  },

  'retail-store': {
    type: 'retail-store',
    name: 'Retail Boutique & Tools Outlet',
    category: 'commercial',
    slotFootprint: 1,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 9200,
    baseMaterialCost: 140,
    dailyEnergyUpkeep: 0.40,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.10,
    dailyComponentsUpkeep: 0.15,
    dailyComputeUpkeep: 0.05,
    dailyStaffingCredits: 140,
    dailyCreditRevenue: 710,
    resourceOutputType: 'credits',
    resourceOutputAmount: 710,
    estimatedPaybackDays: 16,
    resourceSensitivity: 'low',
    maintenanceRisk: 'low',
    primaryEconomicPurpose: 'Retail Sales & Domestic Equipment Turnover',
    description: 'Consumer storefront supplying standardized tools, consumer gear, and manufactured hardware to urban dwellers.',
    tiers: [
      {
        tier: 1,
        name: 'Retail Hardware Outlet',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 710,
        dailyOperatingCredits: 140,
        dailyEnergyUpkeep: 0.40,
        dailyComponentsUpkeep: 0.15,
        unlockedPerks: ['Standard Consumer Hardware', 'Self-Checkout Automated Kiosks'],
        description: 'Standard consumer outlet (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Omni-Channel Department Store',
        upgradeCreditCost: 8200,
        upgradeMaterialCost: 110,
        upgradeComponentsCost: 15,
        dailyCreditRevenue: 1680,
        dailyOperatingCredits: 280,
        dailyEnergyUpkeep: 0.80,
        dailyComponentsUpkeep: 0.30,
        unlockedPerks: ['Bulk Wholesale Discounting', 'Same-Day Drone Delivery Hub'],
        requiredCityPopulation: 12,
        description: 'Expanded department store serving multiple municipal sectors.',
      },
      {
        tier: 3,
        name: 'Cyber-Emporium Flagship',
        upgradeCreditCost: 21000,
        upgradeMaterialCost: 250,
        upgradeComponentsCost: 40,
        upgradeComputeCost: 30,
        dailyCreditRevenue: 3950,
        dailyOperatingCredits: 580,
        dailyEnergyUpkeep: 1.50,
        dailyComponentsUpkeep: 0.60,
        unlockedPerks: ['Augmented Reality Mall Integration', 'Cross-District Logistics Streamlining'],
        requiredCityPopulation: 30,
        requiredPatent: {
          patentId: 'PAT-LOG-01',
          patentName: 'Predictive Autonomous Supply Routing',
          owningCorporationId: 'CORP-NEXUS',
          owningCorporationName: 'Nexus Global Dynamics',
          privateLicenseCostCrd: 5200,
          privateDailyRoyaltyCrd: 75,
          cityCivicLicenseCostCrd: 18000,
          termDays: 30,
          description: 'Predictive inventory caching and autonomous drone swarm routing matrix.',
        },
        description: 'Flagship retail emporium generating massive merchant volume.',
      },
    ],
  },

  'commercial-mall': {
    type: 'commercial-mall',
    name: 'Metropolitan Commercial Galleria',
    category: 'commercial',
    slotFootprint: 4,
    defaultOwnershipClass: 'public_investment',
    tier: 1,
    baseCreditCost: 42000,
    baseMaterialCost: 580,
    dailyEnergyUpkeep: 3.50,
    dailyFoodUpkeep: 0.80,
    dailyMaterialsUpkeep: 0.30,
    dailyComponentsUpkeep: 0.50,
    dailyComputeUpkeep: 0.60,
    dailyStaffingCredits: 600,
    dailyCreditRevenue: 4200,
    resourceOutputType: 'credits',
    resourceOutputAmount: 4200,
    estimatedPaybackDays: 14,
    resourceSensitivity: 'medium',
    maintenanceRisk: 'medium',
    primaryEconomicPurpose: 'Multi-Tenant Commercial Hub & Shareholder Dividends',
    description: 'Expansive multi-tier commercial galleria combining retail boutiques, culinary pavilions, and entertainment theaters.',
    tiers: [
      {
        tier: 1,
        name: 'District Galleria Center',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 4200,
        dailyOperatingCredits: 600,
        dailyEnergyUpkeep: 3.50,
        unlockedPerks: ['Multi-Tenant Merchant Leases', 'Public Crowdfunding Dividends'],
        description: 'Civic commercial mall center.',
      },
      {
        tier: 2,
        name: 'Megacity Galleria Complex',
        upgradeCreditCost: 35000,
        upgradeMaterialCost: 450,
        upgradeComponentsCost: 60,
        upgradeComputeCost: 40,
        dailyCreditRevenue: 8900,
        dailyOperatingCredits: 1100,
        dailyEnergyUpkeep: 5.80,
        unlockedPerks: ['Luxury Brand Concessions', 'City Sales Tax Rebate (+10% Yield)'],
        requiredCityPopulation: 35,
        requiredPatent: {
          patentId: 'PAT-HOLO-01',
          patentName: 'Volumetric Holographic Retail Projection',
          owningCorporationId: 'CORP-TURING',
          owningCorporationName: 'Turing Quantum Systems',
          privateLicenseCostCrd: 8500,
          privateDailyRoyaltyCrd: 120,
          cityCivicLicenseCostCrd: 25000,
          termDays: 30,
          description: 'Multi-spectral volumetric lightfield projection for luxury mall displays.',
        },
        description: 'Planetary shopping landmark with high shareholder dividends.',
      },
    ],
  },

  // ==================== 2. INDUSTRIAL & MANUFACTURING (Resource Security) ====================
  'fabrication-plant': {
    type: 'fabrication-plant',
    name: 'Automated CNC Fabrication Plant',
    category: 'manufacturing',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 13500,
    baseMaterialCost: 240,
    dailyEnergyUpkeep: 2.00,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 1.50,
    dailyComponentsUpkeep: 0.10,
    dailyComputeUpkeep: 0.20,
    dailyStaffingCredits: 150,
    dailyCreditRevenue: 0,
    resourceOutputType: 'components',
    resourceOutputAmount: 2.2,
    estimatedPaybackDays: 18,
    resourceSensitivity: 'high',
    maintenanceRisk: 'medium',
    primaryEconomicPurpose: 'Precision Component Fabrication & Machine Spare Parts',
    description: 'Precision robotics foundry converting raw structural materials into high-grade components for repairs and machine assembly.',
    tiers: [
      {
        tier: 1,
        name: 'CNC Milling Workshop',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 150,
        dailyEnergyUpkeep: 2.00,
        dailyMaterialsUpkeep: 1.50,
        resourceOutputType: 'components',
        resourceOutputAmount: 2.2,
        unlockedPerks: ['Automated 5-Axis Milling', 'Machine Component Stamping'],
        description: 'Standard automated component manufacturing (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Advanced Robotic Fab Line',
        upgradeCreditCost: 12000,
        upgradeMaterialCost: 180,
        upgradeComponentsCost: 25,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 260,
        dailyEnergyUpkeep: 3.40,
        dailyMaterialsUpkeep: 2.60,
        resourceOutputType: 'components',
        resourceOutputAmount: 5.2,
        unlockedPerks: ['Laser Sintering Micro-Assembly', 'Zero-Defect Quality Control (+20% Yield)'],
        requiredCityPopulation: 15,
        description: 'High-throughput robotic line with precision component output.',
      },
      {
        tier: 3,
        name: 'Quantum Nano-Fabrication Complex',
        upgradeCreditCost: 28000,
        upgradeMaterialCost: 380,
        upgradeComponentsCost: 60,
        upgradeComputeCost: 50,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 520,
        dailyEnergyUpkeep: 5.50,
        dailyMaterialsUpkeep: 4.20,
        resourceOutputType: 'components',
        resourceOutputAmount: 11.5,
        unlockedPerks: ['Molecular Reconfigurable Fabs', 'Corporate Machine Blueprint Integration'],
        requiredCityPopulation: 35,
        requiredPatent: {
          patentId: 'PAT-FAB-01',
          patentName: 'Quantum Nano-Fabrication Protocol',
          owningCorporationId: 'CORP-AXIOM',
          owningCorporationName: 'Axiom Heavy Industries',
          privateLicenseCostCrd: 7500,
          privateDailyRoyaltyCrd: 110,
          cityCivicLicenseCostCrd: 24000,
          termDays: 30,
          description: 'Sub-atomic precision laser etching and reconfigurable lattice assemblers.',
        },
        description: 'State-of-the-art quantum nano-foundry.',
      },
    ],
  },

  'chemical-foundry': {
    type: 'chemical-foundry',
    name: 'Catalytic Polymer Foundry',
    category: 'manufacturing',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 14000,
    baseMaterialCost: 220,
    dailyEnergyUpkeep: 2.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.80,
    dailyComponentsUpkeep: 0.15,
    dailyComputeUpkeep: 0.10,
    dailyStaffingCredits: 160,
    dailyCreditRevenue: 0,
    resourceOutputType: 'material',
    resourceOutputAmount: 4.8,
    estimatedPaybackDays: 16,
    resourceSensitivity: 'high',
    maintenanceRisk: 'medium',
    primaryEconomicPurpose: 'Structural Material Synthesis & Construction Feedstock',
    description: 'Chemical synthesis plant processing atmospheric gases and ore feedstocks into reinforced construction materials.',
    tiers: [
      {
        tier: 1,
        name: 'Catalytic Refining Cell',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 160,
        dailyEnergyUpkeep: 2.20,
        resourceOutputType: 'material',
        resourceOutputAmount: 4.8,
        unlockedPerks: ['Thermal Hydrocarbon Cracking', 'Structural Carbon Fiber Weaving'],
        description: 'Standard material synthesis plant (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Graphene Alloy Synthesis Plant',
        upgradeCreditCost: 13500,
        upgradeMaterialCost: 200,
        upgradeComponentsCost: 20,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 290,
        dailyEnergyUpkeep: 3.80,
        resourceOutputType: 'material',
        resourceOutputAmount: 10.5,
        unlockedPerks: ['Graphene Sheet Deposition', 'Continuous Smelting Loop'],
        requiredCityPopulation: 16,
        requiredPatent: {
          patentId: 'PAT-MAT-01',
          patentName: 'CVD Graphene Lattice Synthesis',
          owningCorporationId: 'CORP-AXIOM',
          owningCorporationName: 'Axiom Heavy Industries',
          privateLicenseCostCrd: 6200,
          privateDailyRoyaltyCrd: 90,
          cityCivicLicenseCostCrd: 20000,
          termDays: 30,
          description: 'Chemical vapor deposition reactor growing contiguous graphene sheets at scale.',
        },
        description: 'High-volume graphene and composite material refinery.',
      },
    ],
  },

  // ==================== 3. ENERGY & UTILITIES (Market Stability) ====================
  'solar-array-complex': {
    type: 'solar-array-complex',
    name: 'Solar Concentrator Array',
    category: 'energy',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 10500,
    baseMaterialCost: 190,
    dailyEnergyUpkeep: 0,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.05,
    dailyComponentsUpkeep: 0.10,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 80,
    dailyCreditRevenue: 0,
    resourceOutputType: 'energy',
    resourceOutputAmount: 4.5,
    estimatedPaybackDays: 15,
    resourceSensitivity: 'low',
    maintenanceRisk: 'low',
    primaryEconomicPurpose: 'Clean Photovoltaic Energy & Grid Baseline',
    description: 'High-efficiency photovoltaic collectors feeding clean solar energy directly into local batteries and the municipal grid.',
    tiers: [
      {
        tier: 1,
        name: 'Photovoltaic Collector Field',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 80,
        dailyEnergyUpkeep: 0,
        resourceOutputType: 'energy',
        resourceOutputAmount: 4.5,
        unlockedPerks: ['Multi-Junction Solar Cells', 'Automated Heliostat Tracking'],
        description: 'Standard solar generation field (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Molten Salt Solar Tower',
        upgradeCreditCost: 9500,
        upgradeMaterialCost: 150,
        upgradeComponentsCost: 15,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 140,
        dailyEnergyUpkeep: 0,
        resourceOutputType: 'energy',
        resourceOutputAmount: 10.2,
        unlockedPerks: ['24-Hour Thermal Salt Storage', 'Nighttime Dispatch Balancing'],
        requiredCityPopulation: 14,
        description: 'Thermal salt storage array enabling 24-hour round-the-clock generation.',
      },
      {
        tier: 3,
        name: 'Orbital Reflection Matrix Node',
        upgradeCreditCost: 24000,
        upgradeMaterialCost: 320,
        upgradeComponentsCost: 45,
        upgradeComputeCost: 20,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 280,
        dailyEnergyUpkeep: 0,
        resourceOutputType: 'energy',
        resourceOutputAmount: 22.0,
        unlockedPerks: ['Orbital Mirror Microwave Downlink', 'Zero Transmission Loss Grid Linking'],
        requiredCityPopulation: 30,
        requiredPatent: {
          patentId: 'PAT-NRG-01',
          patentName: 'Microwave Orbital Power Rectenna Protocol',
          owningCorporationId: 'CORP-STELLAR',
          owningCorporationName: 'Stellar Reach Aerospace',
          privateLicenseCostCrd: 6800,
          privateDailyRoyaltyCrd: 95,
          cityCivicLicenseCostCrd: 22000,
          termDays: 30,
          description: 'Phased microwave receiver rectennas capturing continuous orbital solar beams.',
        },
        description: 'High-density orbital beam collector generating massive power surpluses.',
      },
    ],
  },

  'geothermal-grid': {
    type: 'geothermal-grid',
    name: 'Geothermal Core Station',
    category: 'energy',
    slotFootprint: 3,
    defaultOwnershipClass: 'civic',
    tier: 1,
    baseCreditCost: 32000,
    baseMaterialCost: 480,
    dailyEnergyUpkeep: 0,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.20,
    dailyComponentsUpkeep: 0.40,
    dailyComputeUpkeep: 0.20,
    dailyStaffingCredits: 300,
    dailyCreditRevenue: 0,
    resourceOutputType: 'energy',
    resourceOutputAmount: 14.0,
    estimatedPaybackDays: 20,
    resourceSensitivity: 'low',
    maintenanceRisk: 'medium',
    primaryEconomicPurpose: 'Municipal Baseload Energy & Citizen UBI Funding',
    civicBenefit: 'Provides permanent 100% city energy capacity coverage and surplus credit UBI dividends.',
    description: 'Deep borehole geothermal tap generating massive continuous baseload electricity for city residents and public facilities.',
    tiers: [
      {
        tier: 1,
        name: 'Deep Magmatic Well Tap',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 300,
        dailyEnergyUpkeep: 0,
        resourceOutputType: 'energy',
        resourceOutputAmount: 14.0,
        unlockedPerks: ['Supercritical Steam Turbines', 'District Thermal Heating Grid'],
        description: 'Standard municipal geothermal facility (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Supercritical Mantle Generator',
        upgradeCreditCost: 28000,
        upgradeMaterialCost: 380,
        upgradeComponentsCost: 50,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 520,
        dailyEnergyUpkeep: 0,
        resourceOutputType: 'energy',
        resourceOutputAmount: 32.0,
        unlockedPerks: ['Mantle Convection Siphoning', 'City Energy Cost Halved (-50%)'],
        requiredCityPopulation: 25,
        requiredPatent: {
          patentId: 'PAT-GEO-01',
          patentName: 'Supercritical Mantle Heat Exchange Patent',
          owningCorporationId: 'CORP-GENESIS',
          owningCorporationName: 'Genesis Horizon Bio-Systems',
          privateLicenseCostCrd: 9500,
          privateDailyRoyaltyCrd: 150,
          cityCivicLicenseCostCrd: 32000,
          termDays: 30,
          description: 'Direct deep-earth closed-loop heat exchangers tapping supercritical crust fluids.',
        },
        description: 'Mantle generator fueling rapid regional industrial growth.',
      },
    ],
  },

  // ==================== 4. FOOD & AGRO (Biomass Security) ====================
  'vertical-farm': {
    type: 'vertical-farm',
    name: 'Aeroponic Vertical Farm Complex',
    category: 'food',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 11200,
    baseMaterialCost: 180,
    dailyEnergyUpkeep: 1.20,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.10,
    dailyComponentsUpkeep: 0.10,
    dailyComputeUpkeep: 0.10,
    dailyStaffingCredits: 110,
    dailyCreditRevenue: 0,
    resourceOutputType: 'food',
    resourceOutputAmount: 3.8,
    estimatedPaybackDays: 16,
    resourceSensitivity: 'medium',
    maintenanceRisk: 'low',
    primaryEconomicPurpose: 'Fresh Protein, Organic Nutrition & Urban Food Reserves',
    description: 'Automated multi-level aeroponic towers providing organic produce, synthetic biomass, and high-yield protein rations.',
    tiers: [
      {
        tier: 1,
        name: 'Aeroponic Tower Array',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 110,
        dailyEnergyUpkeep: 1.20,
        resourceOutputType: 'food',
        resourceOutputAmount: 3.8,
        unlockedPerks: ['Optimized LED Wavelength Spectral Tuning', 'Closed-Loop Nutrient Mist Recycling'],
        description: 'Standard urban vertical farm (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Automated Agro-Bioreactor Hub',
        upgradeCreditCost: 9800,
        upgradeMaterialCost: 140,
        upgradeComponentsCost: 18,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 190,
        dailyEnergyUpkeep: 2.10,
        resourceOutputType: 'food',
        resourceOutputAmount: 8.5,
        unlockedPerks: ['Cellular Meat Synthesis Vats', 'High-Density Protein Blocks'],
        requiredCityPopulation: 12,
        requiredPatent: {
          patentId: 'PAT-BIO-01',
          patentName: 'Cellular Myocyte Proliferation Patent',
          owningCorporationId: 'CORP-GENESIS',
          owningCorporationName: 'Genesis Horizon Bio-Systems',
          privateLicenseCostCrd: 4800,
          privateDailyRoyaltyCrd: 70,
          cityCivicLicenseCostCrd: 16000,
          termDays: 30,
          description: 'High-density bioreactor tanks multiplying cultured cell structures at rapid scale.',
        },
        description: 'High-volume bioreactor synthesizing cellular agriculture.',
      },
    ],
  },

  // ==================== 5. DATA & COMPUTE (Research & AI) ====================
  'server-farm': {
    type: 'server-farm',
    name: 'Liquid-Cooled Neural Data Center',
    category: 'compute',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 14500,
    baseMaterialCost: 220,
    dailyEnergyUpkeep: 3.00,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.05,
    dailyComponentsUpkeep: 0.20,
    dailyComputeUpkeep: 0,
    dailyStaffingCredits: 180,
    dailyCreditRevenue: 0,
    resourceOutputType: 'compute',
    resourceOutputAmount: 5.0,
    estimatedPaybackDays: 17,
    resourceSensitivity: 'high',
    maintenanceRisk: 'medium',
    primaryEconomicPurpose: 'High-Throughput Quantum & Neural Compute Generation',
    description: 'Immersion-cooled neural server farm providing high-performance telemetry, synthetic compute, and R&D acceleration.',
    tiers: [
      {
        tier: 1,
        name: 'Submerged Server Cluster',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 180,
        dailyEnergyUpkeep: 3.00,
        resourceOutputType: 'compute',
        resourceOutputAmount: 5.0,
        unlockedPerks: ['Dielectric Fluid Immersion Cooling', 'Distributed Vector Crunching'],
        description: 'Standard compute cluster (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Quantum Qubit Compute Array',
        upgradeCreditCost: 14000,
        upgradeMaterialCost: 210,
        upgradeComponentsCost: 35,
        upgradeComputeCost: 30,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 340,
        dailyEnergyUpkeep: 5.20,
        resourceOutputType: 'compute',
        resourceOutputAmount: 12.0,
        unlockedPerks: ['Cryogenic Superconducting Qubits', 'Corporate Research Speed Bonus (+25%)'],
        requiredCityPopulation: 18,
        requiredPatent: {
          patentId: 'PAT-DAT-01',
          patentName: 'Cryogenic Superconducting Qubit Interconnect',
          owningCorporationId: 'CORP-TURING',
          owningCorporationName: 'Turing Quantum Systems',
          privateLicenseCostCrd: 6900,
          privateDailyRoyaltyCrd: 100,
          cityCivicLicenseCostCrd: 22000,
          termDays: 30,
          description: 'Dilution refrigeration systems stabilizing 128-qubit quantum coherency gates.',
        },
        description: 'Quantum qubit processor hub accelerating technology R&D.',
      },
      {
        tier: 3,
        name: 'Photonic Artificial Supercluster',
        upgradeCreditCost: 32000,
        upgradeMaterialCost: 420,
        upgradeComponentsCost: 75,
        upgradeComputeCost: 80,
        dailyCreditRevenue: 0,
        dailyOperatingCredits: 680,
        dailyEnergyUpkeep: 8.50,
        resourceOutputType: 'compute',
        resourceOutputAmount: 28.0,
        unlockedPerks: ['Optical Photonic Interconnects', 'Planetary AI Predictive Optimization'],
        requiredCityPopulation: 40,
        requiredPatent: {
          patentId: 'PAT-DAT-02',
          patentName: 'Integrated Photonic Neural Processor Core',
          owningCorporationId: 'CORP-TURING',
          owningCorporationName: 'Turing Quantum Systems',
          privateLicenseCostCrd: 12000,
          privateDailyRoyaltyCrd: 180,
          cityCivicLicenseCostCrd: 40000,
          termDays: 30,
          description: 'Laser-driven optical matrix multipliers achieving exaflop inference throughput.',
        },
        description: 'Planetary-scale photonic supercluster powering advanced AI automation.',
      },
    ],
  },

  // ==================== 6. MEDICAL & HEALTHCARE (City Health Index) ====================
  'medical-clinic': {
    type: 'medical-clinic',
    name: 'Bionic Medical Center & Clinic',
    category: 'medical',
    slotFootprint: 2,
    defaultOwnershipClass: 'private',
    tier: 1,
    baseCreditCost: 16000,
    baseMaterialCost: 240,
    dailyEnergyUpkeep: 1.50,
    dailyFoodUpkeep: 0.20,
    dailyMaterialsUpkeep: 0.10,
    dailyComponentsUpkeep: 0.25,
    dailyComputeUpkeep: 0.50,
    dailyStaffingCredits: 220,
    dailyCreditRevenue: 1200,
    resourceOutputType: 'credits',
    resourceOutputAmount: 1200,
    estimatedPaybackDays: 18,
    resourceSensitivity: 'medium',
    maintenanceRisk: 'low',
    primaryEconomicPurpose: 'Urban Healthcare, Longevity & Disease Protection',
    civicBenefit: 'Increases city health score by +15 points and safeguards resident longevity.',
    description: 'Advanced medical clinic specializing in cybernetic maintenance, trauma stabilization, and cellular anti-aging therapies.',
    tiers: [
      {
        tier: 1,
        name: 'Community Cyber-Clinic',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 1200,
        dailyOperatingCredits: 220,
        dailyEnergyUpkeep: 1.50,
        unlockedPerks: ['Trauma Stabilization Pods', 'Automated Cyber-Surgical Arms'],
        description: 'Standard bionic medical clinic (EARTH Open Technology).',
      },
      {
        tier: 2,
        name: 'Regenerative Bio-Hospital',
        upgradeCreditCost: 15500,
        upgradeMaterialCost: 230,
        upgradeComponentsCost: 30,
        upgradeComputeCost: 25,
        dailyCreditRevenue: 2850,
        dailyOperatingCredits: 420,
        dailyEnergyUpkeep: 2.80,
        unlockedPerks: ['Organ Cloning Vats', 'Epidemic Risk Inoculation (-80% Crisis Risk)'],
        requiredCityPopulation: 20,
        requiredPatent: {
          patentId: 'PAT-MED-01',
          patentName: 'Autologous Organ Cloning & Telomere Repair',
          owningCorporationId: 'CORP-GENESIS',
          owningCorporationName: 'Genesis Horizon Bio-Systems',
          privateLicenseCostCrd: 7200,
          privateDailyRoyaltyCrd: 105,
          cityCivicLicenseCostCrd: 26000,
          termDays: 30,
          description: 'Rapid pluripotent stem cell bioprinters creating immunocompatible replacement organs.',
        },
        description: 'Comprehensive bio-hospital securing planetary health scores.',
      },
    ],
  },

  // ==================== 7. CIVIC INFRASTRUCTURE & MEGAPROJECTS (Citizen Dividends) ====================
  'transit-hyperloop': {
    type: 'transit-hyperloop',
    name: 'Inter-District Hyperloop Terminal',
    category: 'civic',
    slotFootprint: 3,
    defaultOwnershipClass: 'public_investment',
    tier: 1,
    baseCreditCost: 38000,
    baseMaterialCost: 520,
    dailyEnergyUpkeep: 4.00,
    dailyFoodUpkeep: 0,
    dailyMaterialsUpkeep: 0.30,
    dailyComponentsUpkeep: 0.50,
    dailyComputeUpkeep: 0.60,
    dailyStaffingCredits: 500,
    dailyCreditRevenue: 3200,
    resourceOutputType: 'credits',
    resourceOutputAmount: 3200,
    estimatedPaybackDays: 16,
    resourceSensitivity: 'medium',
    maintenanceRisk: 'medium',
    primaryEconomicPurpose: 'High-Speed Logistics & Public Passenger Dividends',
    civicBenefit: 'Reduces market trade fees by 1.5% and links city districts into a unified economic hub.',
    description: 'Pneumatic vacuum transit terminal transporting citizens and cargo between urban quadrant zones at supersonic speeds.',
    tiers: [
      {
        tier: 1,
        name: 'District Hyperloop Hub',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 3200,
        dailyOperatingCredits: 500,
        dailyEnergyUpkeep: 4.00,
        unlockedPerks: ['Supersonic Maglev Transit', 'Public Crowdfunded Equity Shares'],
        description: 'Standard hyperloop terminal.',
      },
      {
        tier: 2,
        name: 'Trans-Continental Express Terminal',
        upgradeCreditCost: 34000,
        upgradeMaterialCost: 450,
        upgradeComponentsCost: 65,
        upgradeComputeCost: 45,
        dailyCreditRevenue: 7600,
        dailyOperatingCredits: 950,
        dailyEnergyUpkeep: 6.80,
        unlockedPerks: ['Heavy Cargo Freight Integration', 'Trade Tariff Rebate (-25%)'],
        requiredCityPopulation: 30,
        requiredPatent: {
          patentId: 'PAT-MAG-01',
          patentName: 'Pneumatic Low-Pressure Maglev Propulsion',
          owningCorporationId: 'CORP-NEXUS',
          owningCorporationName: 'Nexus Global Dynamics',
          privateLicenseCostCrd: 8500,
          privateDailyRoyaltyCrd: 130,
          cityCivicLicenseCostCrd: 30000,
          termDays: 30,
          description: 'Near-vacuum sealed tube depressurization and superconducting levitation tracks.',
        },
        description: 'Massive trans-continental hub connecting major metropolitan trade corridors.',
      },
    ],
  },

  // ==================== 8. ORBITAL & ADVANCED (High-Tier Prestige & Multi-Layer Unlocks) ====================
  'orbital-spaceport': {
    type: 'orbital-spaceport',
    name: 'Equatorial Orbital Spaceport',
    category: 'orbital',
    slotFootprint: 6,
    defaultOwnershipClass: 'public_investment',
    tier: 1,
    baseCreditCost: 95000,
    baseMaterialCost: 1200,
    dailyEnergyUpkeep: 10.00,
    dailyFoodUpkeep: 1.00,
    dailyMaterialsUpkeep: 1.20,
    dailyComponentsUpkeep: 1.50,
    dailyComputeUpkeep: 2.50,
    dailyStaffingCredits: 1500,
    dailyCreditRevenue: 10500,
    resourceOutputType: 'credits',
    resourceOutputAmount: 10500,
    estimatedPaybackDays: 12,
    resourceSensitivity: 'high',
    maintenanceRisk: 'high',
    primaryEconomicPurpose: 'Orbital Shuttles, Off-World Mining Logistics & High Prestige',
    civicBenefit: 'Unlocks planetary asteroid mining routes, deep space telemetry, and planetary prestige.',
    description: 'Equatorial launch complex capable of sending heavy SSTO cargo shuttles into low Earth orbit and deep space transit trajectories.',
    requiredPatent: {
      patentId: 'PAT-SSTO-01',
      patentName: 'Linear Aerospike SSTO Propulsion Protocol',
      owningCorporationId: 'CORP-STELLAR',
      owningCorporationName: 'Stellar Reach Aerospace',
      privateLicenseCostCrd: 15000,
      privateDailyRoyaltyCrd: 250,
      cityCivicLicenseCostCrd: 55000,
      termDays: 30,
      description: 'Altitude-compensating linear aerospike engines enabling single-stage orbital ascent.',
    },
    tiers: [
      {
        tier: 1,
        name: 'Sub-Orbital Launch Complex',
        upgradeCreditCost: 0,
        upgradeMaterialCost: 0,
        dailyCreditRevenue: 10500,
        dailyOperatingCredits: 1500,
        dailyEnergyUpkeep: 10.00,
        unlockedPerks: ['SSTO Cargo Shuttles', 'Orbital Satellite Deployment Contracts'],
        description: 'First-stage heavy launch platform.',
      },
      {
        tier: 2,
        name: 'Planetary Space Elevator Anchor',
        upgradeCreditCost: 85000,
        upgradeMaterialCost: 980,
        upgradeComponentsCost: 140,
        upgradeComputeCost: 120,
        dailyCreditRevenue: 24500,
        dailyOperatingCredits: 2800,
        dailyEnergyUpkeep: 16.00,
        unlockedPerks: ['Carbon Nanotube Tether Car', 'Zero-G Orbital Manufacturing Bonus (+40%)'],
        requiredCityPopulation: 50,
        requiredPatent: {
          patentId: 'PAT-ELEV-01',
          patentName: 'Macroscopic Carbon Nanotube Ribbon Tether',
          owningCorporationId: 'CORP-STELLAR',
          owningCorporationName: 'Stellar Reach Aerospace',
          privateLicenseCostCrd: 25000,
          privateDailyRoyaltyCrd: 400,
          cityCivicLicenseCostCrd: 85000,
          termDays: 30,
          description: 'Flawless 36,000 km carbon nanotube composite ribbon with magnetic climber rails.',
        },
        description: 'Planetary space elevator anchor siphoning orbital commodities directly to earth surface.',
      },
    ],
  },
};

// Research is directly usable by the owner. Patent gates and licensing are
// retired, so legacy catalog fixtures must not leak into API responses.
for (const building of Object.values(BUILDING_CATALOG)) {
  delete building.requiredPatent;
  for (const tier of building.tiers) delete tier.requiredPatent;
}

export const PATENT_CATALOG: Record<string, RequiredPatentSpec> = Object.values(BUILDING_CATALOG).reduce(
  (acc, bld) => {
    if (bld.requiredPatent) {
      acc[bld.requiredPatent.patentId] = bld.requiredPatent;
    }
    for (const tier of bld.tiers) {
      if (tier.requiredPatent) {
        acc[tier.requiredPatent.patentId] = tier.requiredPatent;
      }
    }
    return acc;
  },
  {} as Record<string, RequiredPatentSpec>,
);
