export type BuildingCategory = 'commercial' | 'industrial' | 'high_tech' | 'municipal_megaproject';
export type OwnershipType = 'private' | 'municipal' | 'corporate';

export interface BuildingCatalogItem {
  type: string;
  name: string;
  category: BuildingCategory;
  tier: number;
  baseCreditCost: number;
  baseMaterialCost: number;
  maxStaffSlots: number;
  upkeepEnergy: number;
  upkeepFood: number;
  upkeepMaterials: number;
  upkeepComponents: number;
  upkeepCompute: number;
  baseDailyRevenueCrd: number;
  primaryOutput: string;
  description: string;
  civicBenefit?: string;
  requiredTech?: string;
}

export const BUILDING_CATALOG: Record<string, BuildingCatalogItem> = {
  // --- COMMERCIAL REAL ESTATE ---
  'restaurant': {
    type: 'restaurant',
    name: 'Bistro & Molecular Restaurant',
    category: 'commercial',
    tier: 1,
    baseCreditCost: 8500,
    baseMaterialCost: 120,
    maxStaffSlots: 4,
    upkeepEnergy: 0.50,
    upkeepFood: 0.25,
    upkeepMaterials: 0,
    upkeepComponents: 0,
    upkeepCompute: 0,
    baseDailyRevenueCrd: 450,
    primaryOutput: 'credits',
    description: 'Specialized molecular dining establishment that converts energy and biomass into liquid credit revenue from resident citizens.',
  },
  'retail-store': {
    type: 'retail-store',
    name: 'Retail Boutique & Department Store',
    category: 'commercial',
    tier: 1,
    baseCreditCost: 9200,
    baseMaterialCost: 140,
    maxStaffSlots: 4,
    upkeepEnergy: 0.40,
    upkeepFood: 0,
    upkeepMaterials: 0,
    upkeepComponents: 0.15,
    upkeepCompute: 0,
    baseDailyRevenueCrd: 520,
    primaryOutput: 'credits',
    description: 'Consumer goods outlet offering manufactured components and standard tools to city dwellers.',
  },
  'commercial-mall': {
    type: 'commercial-mall',
    name: 'Metropolitan Commercial Mall',
    category: 'commercial',
    tier: 3,
    baseCreditCost: 48000,
    baseMaterialCost: 750,
    maxStaffSlots: 16,
    upkeepEnergy: 2.50,
    upkeepFood: 1.00,
    upkeepMaterials: 0,
    upkeepComponents: 0.50,
    upkeepCompute: 0.20,
    baseDailyRevenueCrd: 3200,
    primaryOutput: 'credits',
    description: 'Massive multi-lot shopping and dining concourse generating substantial commercial revenue and municipal sales tax.',
    requiredTech: 'Automated Assembly',
  },
  'holo-entertainment': {
    type: 'holo-entertainment',
    name: 'Holo-Entertainment Arena',
    category: 'commercial',
    tier: 2,
    baseCreditCost: 22000,
    baseMaterialCost: 320,
    maxStaffSlots: 8,
    upkeepEnergy: 1.80,
    upkeepFood: 0,
    upkeepMaterials: 0,
    upkeepComponents: 0.20,
    upkeepCompute: 0.80,
    baseDailyRevenueCrd: 1650,
    primaryOutput: 'credits',
    description: 'Immersive entertainment venue hosting algorithmic concerts and sporting tournaments.',
  },

  // --- INDUSTRIAL & REFINERIES ---
  'fabrication-plant': {
    type: 'fabrication-plant',
    name: 'Automated Fabrication Plant',
    category: 'industrial',
    tier: 1,
    baseCreditCost: 11000,
    baseMaterialCost: 180,
    maxStaffSlots: 6,
    upkeepEnergy: 2.00,
    upkeepFood: 0,
    upkeepMaterials: 1.50,
    upkeepComponents: 0,
    upkeepCompute: 0.10,
    baseDailyRevenueCrd: 750,
    primaryOutput: 'components',
    description: 'Industrial manufacturing facility engineered to house precision CNC cells and multi-arm assembly lines.',
  },
  'chemical-foundry': {
    type: 'chemical-foundry',
    name: 'Deep Chemical & Alloy Foundry',
    category: 'industrial',
    tier: 2,
    baseCreditCost: 24000,
    baseMaterialCost: 380,
    maxStaffSlots: 8,
    upkeepEnergy: 3.20,
    upkeepFood: 0,
    upkeepMaterials: 3.00,
    upkeepComponents: 0.25,
    upkeepCompute: 0.15,
    baseDailyRevenueCrd: 1400,
    primaryOutput: 'material',
    description: 'High-temperature metallurgical forge producing titanium-carbon composites and specialized alloys.',
  },
  'protein-refinery': {
    type: 'protein-refinery',
    name: 'Biochemical Protein Refinery',
    category: 'industrial',
    tier: 2,
    baseCreditCost: 18500,
    baseMaterialCost: 290,
    maxStaffSlots: 6,
    upkeepEnergy: 1.60,
    upkeepFood: 0.40,
    upkeepMaterials: 0.20,
    upkeepComponents: 0.10,
    upkeepCompute: 0,
    baseDailyRevenueCrd: 1100,
    primaryOutput: 'food',
    description: 'Sterile chemical processing plant that synthesizes food reserves and organic polymers.',
  },
  'quantum-fab': {
    type: 'quantum-fab',
    name: 'Quantum Microelectronics Fab',
    category: 'industrial',
    tier: 3,
    baseCreditCost: 52000,
    baseMaterialCost: 820,
    maxStaffSlots: 12,
    upkeepEnergy: 4.00,
    upkeepFood: 0,
    upkeepMaterials: 0.80,
    upkeepComponents: 0.50,
    upkeepCompute: 1.80,
    baseDailyRevenueCrd: 3600,
    primaryOutput: 'components',
    description: 'Sub-nanometer lithography cleanroom producing advanced quantum cores and AI matrices.',
    requiredTech: 'Cryogenic Supercomputing',
  },

  // --- HIGH-TECH & INTELLIGENCE ---
  'server-farm': {
    type: 'server-farm',
    name: 'Neural Data Center & Server Farm',
    category: 'high_tech',
    tier: 1,
    baseCreditCost: 12500,
    baseMaterialCost: 190,
    maxStaffSlots: 6,
    upkeepEnergy: 3.00,
    upkeepFood: 0,
    upkeepMaterials: 0,
    upkeepComponents: 0.20,
    upkeepCompute: 0,
    baseDailyRevenueCrd: 800,
    primaryOutput: 'compute',
    description: 'Liquid-cooled data facility providing high-throughput computational telemetry.',
  },
  'corporate-lab': {
    type: 'corporate-lab',
    name: 'Corporate R&D Laboratory',
    category: 'high_tech',
    tier: 2,
    baseCreditCost: 26000,
    baseMaterialCost: 390,
    maxStaffSlots: 8,
    upkeepEnergy: 2.20,
    upkeepFood: 0,
    upkeepMaterials: 0.10,
    upkeepComponents: 0.30,
    upkeepCompute: 1.50,
    baseDailyRevenueCrd: 1800,
    primaryOutput: 'compute',
    description: 'Advanced laboratory facility dedicated to researching corporate patent commons.',
  },
  'orbital-observatory': {
    type: 'orbital-observatory',
    name: 'Orbital Uplink Observatory',
    category: 'high_tech',
    tier: 3,
    baseCreditCost: 55000,
    baseMaterialCost: 880,
    maxStaffSlots: 10,
    upkeepEnergy: 3.50,
    upkeepFood: 0,
    upkeepMaterials: 0.20,
    upkeepComponents: 0.60,
    upkeepCompute: 1.00,
    baseDailyRevenueCrd: 3800,
    primaryOutput: 'compute',
    description: 'Deep-space communication array linking planetary operations with orbital constellations.',
    requiredTech: 'Orbital Logistics',
  },

  // --- MUNICIPAL MEGAPROJECTS (CIVIC) ---
  'geothermal-grid': {
    type: 'geothermal-grid',
    name: 'Central Geothermal Power Grid',
    category: 'municipal_megaproject',
    tier: 3,
    baseCreditCost: 75000,
    baseMaterialCost: 1200,
    maxStaffSlots: 16,
    upkeepEnergy: 0,
    upkeepFood: 0,
    upkeepMaterials: 1.50,
    upkeepComponents: 0.50,
    upkeepCompute: 0.20,
    baseDailyRevenueCrd: 850,
    primaryOutput: 'energy',
    description: 'Massive civic deep-bore thermal tapping facility supplying base-load energy to the entire municipality.',
    civicBenefit: 'Boosts City Energy Capacity (+50) and lowers grid utility tariffs for all residents.',
  },
  'transit-terminus': {
    type: 'transit-terminus',
    name: 'Central Transit & Logistics Hub',
    category: 'municipal_megaproject',
    tier: 2,
    baseCreditCost: 60000,
    baseMaterialCost: 950,
    maxStaffSlots: 20,
    upkeepEnergy: 2.00,
    upkeepFood: 0,
    upkeepMaterials: 0.50,
    upkeepComponents: 0.80,
    upkeepCompute: 0.50,
    baseDailyRevenueCrd: 1200,
    primaryOutput: 'credits',
    description: 'Automated Maglev and drone logistics terminal facilitating rapid freight transit across the city.',
    civicBenefit: 'Boosts City Connectivity (+60) and reduces business freight friction by 25%.',
  },
  'general-hospital': {
    type: 'general-hospital',
    name: 'Metropolitan General Hospital',
    category: 'municipal_megaproject',
    tier: 2,
    baseCreditCost: 70000,
    baseMaterialCost: 1100,
    maxStaffSlots: 16,
    upkeepEnergy: 3.00,
    upkeepFood: 1.50,
    upkeepMaterials: 0.20,
    upkeepComponents: 1.00,
    upkeepCompute: 1.00,
    baseDailyRevenueCrd: 600,
    primaryOutput: 'credits',
    description: 'State-of-the-art public healthcare complex providing automated triage and medical cybernetics.',
    civicBenefit: 'Boosts City Health Capacity (+50) and halts natural health degradation for resident citizens.',
  },
  'orbital-spaceport': {
    type: 'orbital-spaceport',
    name: 'Planetary Spaceport & Orbital Drydock',
    category: 'municipal_megaproject',
    tier: 4,
    baseCreditCost: 150000,
    baseMaterialCost: 2500,
    maxStaffSlots: 32,
    upkeepEnergy: 6.00,
    upkeepFood: 0,
    upkeepMaterials: 1.00,
    upkeepComponents: 3.00,
    upkeepCompute: 2.50,
    baseDailyRevenueCrd: 6500,
    primaryOutput: 'credits',
    description: 'Sovereign aerospace hub capable of handling sub-orbital shuttles and assembling interplanetary transports.',
    civicBenefit: 'Unlocks orbital trade contracts and provides high-wage public shifts for resident robots.',
    requiredTech: 'Orbital Logistics',
  },
};
